{
  "hash": "bc0467dae20db4041099facf4f4e52ee",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Glottal-to-Noise Excitation Ratio (GNE)\"\nexecute:\n  echo: true\njupyter: python3\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code for this figure\"\n---\n\n::: {.callout-note}\n**Living draft.** This chapter reflects the sources cited below and will be\nrevised as further sources are incorporated. Found an error? Use the *Report an\nissue* link in the sidebar.\n:::\n\n\n## Definition\n\nGNE asks a question none of the other noise measures can answer cleanly: **is\nthis signal driven by vocal fold vibration, or by turbulent air?** It\nquantifies the amount of voice excitation by glottal oscillations against\nexcitation by turbulent noise [@michaelis1997gne]. A clear, non-breathy voice\ngives a high GNE.\n\nWhat makes it unusual is what it ignores. Jitter and shimmer describe a voice\nthat is *irregular*; the classical noise measures describe a voice that is\n*noisy*; and most of them cannot tell the two apart. GNE was built so that\ndeviations from periodicity do not influence the degree of turbulence it\nmeasures [@michaelis1997gne]. Its authors put the consequence bluntly: in\nnormal voices a jitter up to 1% and a shimmer up to 3% can be observed, and\neven at those everyday levels the normalized noise energy (NNE) and the\ncepstrum-based harmonics-to-noise ratio (CHNR) cannot distinguish variation in\namplitude or periodicity from added noise — so a proper evaluation of voice\nquality cannot be obtained from them, and in particular they cannot reliably\nseparate pathologies that produce turbulent noise from those that produce\nirregular glottal excitation [@michaelis1997gne].\n\nGNE is also not a model of perception. A related interband-correlation\ntechnique had been proposed as a model of roughness perception; the GNE\napproach is motivated only by the speech production process and signal theory\nand does not intend to model any perceptive effect [@michaelis1997gne].\n\n## How it is computed\n\nThe method rests on the correlation between **Hilbert envelopes of different\nfrequency bands** [@michaelis1997gne]. A single glottal closure excites every\nfrequency channel at once, so all the envelopes share a shape and correlate\nhighly. Turbulent noise excites each channel with its own narrow-band noise,\nand those are uncorrelated — provided the windows defining adjacent channels\ndo not overlap too much [@michaelis1997gne].\n\nSix steps [@michaelis1997gne]:\n\n1. Down-sample to 10 kHz.\n2. Inverse filter the signal, by linear prediction of order 13 computed with\n   the autocorrelation method over a 30-ms Hann window at 10-ms shift. This\n   flattens the spectrum into a train of near-delta pulses whose peaks\n   presumably mark the instants of glottal closure.\n3. Compute the Hilbert envelopes of frequency bands of fixed bandwidth at\n   different centre frequencies.\n4. For every pair of envelopes whose centre frequencies differ by at least\n   half the bandwidth, compute the cross-correlation.\n5. Take the maximum of each correlation function, searching a delay of\n   −3 to +3 samples (±0.3 ms), because the envelopes differ in phase.\n6. Take the maximum of those maxima. That is GNE.\n\nStep 1 has a practical consequence worth noting: the authors observe that\nrecovery of the pulse train is imperfect for material digitized at 48 or\n50 kHz, because voice energy nearly vanishes above 5 kHz [@michaelis1997gne].\n\n### The bandwidth is part of the measure\n\nGNE is bounded above by 1 and reaches 0. How it behaves between those bounds\ndepends on the **envelope bandwidth**, which is not a setting but a choice of\nmeasure:\n\n| Bandwidth | Centre frequencies | Behaviour on synthesized signals |\n|---|---|---|\n| 1000 Hz | 500–4500 Hz, 80-Hz steps | falls monotonically from 0.9999 to zero as the relative noise level rises from −50 to +20 dB; falls with rising *f*~0~ |\n| 2000 Hz | 1000–4000 Hz, 100-Hz steps | falls from 0.998 to zero; falls with rising *f*~0~ |\n| 3000 Hz | 1500–3500 Hz, 100-Hz steps | weakest dependence on *f*~0~; smallest dynamic range |\n\n: The three bandwidth conditions of @michaelis1997gne. {#tbl-gne-bandwidths}\n\nThese are synthesized signals, varied in noise level, *f*~0~, jitter and\nshimmer. They show how the measure behaves; **they are not reference values for\nhuman speakers.**\n\n### Two names, one measure\n\nThis is the trap the literature sets. The same computation is named by its\nbandwidth in one tradition and by its maximum frequency in the other:\n\n- **\"GNE 1000 Hz\"** — Praat `To Harmonicity (gne): 500, 4500, 1000, 80`,\n  reduced by `Get maximum`.\n- **\"GNEmax-4500 Hz\"** — the term the [ABI](abi.qmd) uses, and the call the\n  ABI's own Praat script issues: `500, 4500, 1000, 80`, reduced by\n  `Get maximum`.\n\nThey are the same call and the same reduction [@abreu2022voxmoreplugin]. A\nreader meeting both names in two papers is meeting one measure. A reader\nmeeting **\"GNE 2000 Hz\"** is not — that is a different measure.\n\n## What it captures\n\n**Independence from perturbation, as a measured property.** GNE assesses\nadditive noise independently of jitter and shimmer, where NNE and CHNR do not\n[@michaelis1998features]. Correlations between any GNE measure and any jitter\nor shimmer measure were insignificant for the normal group and significantly\nlower than the other noise measures' for the pathological group\n[@michaelis1998features]. This is the property that separates GNE from the\nrest of the noise family — and it is why a low GNE alongside normal\nperturbation values is informative rather than contradictory.\n\nThe independence is not absolute. On synthesized signals at a 1000-Hz\nbandwidth, **GNE falls once jitter exceeds about 1%**, and the dependence\ngrows with *f*~0~ [@michaelis1997gne]. Since normal voices reach about 1%\njitter, the onset sits at the edge of the normal range rather than safely\noutside it. \"Independent of jitter and shimmer\", as the secondary literature\noften puts it, is true of shimmer and approximately true of jitter.\n\n**The noise axis of the hoarseness diagram.** The diagram is a two-dimensional\nplane: its horizontal axis is the *irregularity component*, built from jitter,\nshimmer and mean period correlation over a waveform-matching segmentation into\nglottal cycles, and its vertical axis is the *noise component*, which is GNE\n[@frohlich2000hoarseness]. GNE is not merely used in the diagram; it is the\nwhole noise dimension. Its authors state the reason directly: two axes can\nonly vary independently if the noise axis is built from a measure that\nperturbation does not move [@frohlich2000hoarseness].\n\n**Bandwidth selects the percept.** Meta-analytically, GNE at a 1000-Hz\nbandwidth is among the strongest predictors of perceived **roughness**\n(weighted *r* = .65, two studies) and at 3000 Hz among the strongest of\nperceived **breathiness** (.73, two studies) [@barsties2018meta]. Of 86\nacoustic measures reviewed for roughness and 85 for breathiness on sustained\nvowels, GNE 1000 was one of 13 named most promising for roughness and GNE 3000\none of 12 for breathiness [@barsties2018meta].\n\n**A real irregular voice.** Comparing a normal voice with a recording of vocal\nfry, the harmonics in the fry spectrum are broadened by jitter, but the Hilbert\nenvelopes stay similar — so GNE is about the same for both, while NNE and CHNR\noverestimate the noise energy [@michaelis1997gne].\n\n## Read the scale before reading any number {#sec-gne-scale}\n\n::: {.callout-important}\n**Two incompatible scales are in use.** A GNE value on one is meaningless on\nthe other, and the published normative values are on the one clinicians are\nleast likely to expect.\n:::\n\n| Scale | Range | Direction | Reported by |\n|---|---|---|---|\n| **GNE**, the raw correlation maximum | 0 to just under 1 | higher is cleaner | Praat `To Harmonicity (gne)`, the ABI script, VOXplot, VoxMore |\n| **GNEl = 10·log~10~(1 − GNE)** | negative | *more negative* is cleaner | @godino2010gne |\n\n: The two GNE scales. {#tbl-gne-scales}\n\nThe log transform is not an eccentricity of one paper: the Göttingen group's\nown feature table gives GNE the transform log(1 − *x*)\n[@michaelis1998features], and the original paper plots its results as 1 − GNE\non a logarithmic axis [@michaelis1997gne].\n\n**Convert before comparing:** GNE = 1 − 10^(GNEl/10)^. A GNEl of −21.28 is a\nGNE of 0.9926. Converting fixes the scale and nothing else — window length,\nbandwidth, frequency step and software still differ between every pair of\nsources below.\n\n::: {#cell-fig-gne-scale .cell execution_count=2}\n``` {.python .cell-code}\nto_gne = lambda l: 1 - 10 ** (np.asarray(l) / 10.0)\nmarks = [(-21.28, vs.BLUE), (-17.92, vs.BLUE), (-14.17, vs.ORANGE)]\n\nfig, (axA, axB) = plt.subplots(\n    1, 2, figsize=(7.4, 3.6), gridspec_kw={\"width_ratios\": [1.15, 1.0]})\n\n# A: the transform\nl = np.linspace(-30, -5, 600)\naxA.plot(to_gne(l), l, color=vs.INK, lw=1.6, zorder=3)\nfor gl, c in marks:\n    g = float(to_gne(gl))\n    axA.plot([g, g], [-30, gl], color=c, lw=1.0, ls=\":\", zorder=2)\n    axA.plot([0.94, g], [gl, gl], color=c, lw=1.0, ls=\":\", zorder=2)\n    axA.plot([g], [gl], \"o\", ms=5, color=c, zorder=4,\n             markeredgecolor=\"white\", markeredgewidth=0.8)\naxA.set_xlim(0.94, 1.0); axA.set_ylim(-30, -5)\naxA.set_xlabel(\"GNE   (correlation maximum)\")\naxA.set_ylabel(\"GNEl  =  10\\u00b7log\\u2081\\u2080(1 \\u2212 GNE)   [dB]\")\naxA.set_title(\"The transform\")\nvs.style_axes(axA)\n\n# B: the same values on GNE's full scale and on GNEl\naxB.set_xlim(-0.03, 1.03); axB.set_ylim(0, 1); axB.axis(\"off\")\naxB.set_title(\"Same voices, two rulers\")\n\ny_top, y_bot = 0.66, 0.30\nL_NEAR, L_FAR = -5.0, -30.0        # reversed, so cleaner lies to the right on both\nx_gne  = lambda g: g               # GNE on its full nominal 0-1 scale\nx_gnel = lambda v: (v - L_NEAR) / (L_FAR - L_NEAR)\n\nfor y, lab, lo, hi in ((y_top, \"GNE\", \"0\", \"1\"),\n                       (y_bot, \"GNEl  [dB]\", \"\\u22125\", \"\\u221230\")):\n    axB.plot([0, 1], [y, y], color=vs.MUTED, lw=1.2, solid_capstyle=\"butt\")\n    axB.text(-0.03, y + 0.075, lab, color=vs.INK, fontsize=8.5, va=\"bottom\")\n    axB.text(0, y - 0.05, lo, color=vs.MUTED, fontsize=7.5, ha=\"center\", va=\"top\")\n    axB.text(1, y - 0.05, hi, color=vs.MUTED, fontsize=7.5, ha=\"center\", va=\"top\")\n\nfor i, (gl, c) in enumerate(marks):\n    g = float(to_gne(gl))\n    xt, xb = x_gne(g), x_gnel(gl)\n    axB.plot([xt, xb], [y_top - 0.03, y_bot + 0.03], color=c, lw=1.0,\n             alpha=0.8, zorder=2)\n    for x, y in ((xt, y_top), (xb, y_bot)):\n        axB.plot([x], [y], \"o\", ms=5, color=c, zorder=3,\n                 markeredgecolor=\"white\", markeredgewidth=0.8)\n    dy = 0.075 if i % 2 == 0 else 0.155\n    axB.text(xb, y_bot - dy, f\"{gl:.2f}\", color=c, fontsize=7.5,\n             ha=\"center\", va=\"top\")\n\ng_lo, g_hi = float(to_gne(-14.17)), float(to_gne(-21.28))\naxB.plot([g_lo, g_hi], [y_top + 0.05, y_top + 0.05], color=vs.INK, lw=2.2,\n         solid_capstyle=\"butt\", zorder=3)\naxB.annotate(f\"all three inside {g_hi - g_lo:.3f} of GNE\",\n             xy=((g_lo + g_hi) / 2, y_top + 0.065), xytext=(0.70, y_top + 0.25),\n             color=vs.INK, fontsize=8, ha=\"right\",\n             arrowprops=dict(arrowstyle=\"->\", color=vs.INK, lw=0.8,\n                             shrinkA=2, shrinkB=1))\n\naxB.legend(handles=[Line2D([], [], marker=\"o\", ls=\"\", ms=5, color=vs.BLUE,\n                           label=\"Normal group\"),\n                    Line2D([], [], marker=\"o\", ls=\"\", ms=5, color=vs.ORANGE,\n                           label=\"Pathological group\")],\n           loc=\"lower center\", bbox_to_anchor=(0.5, -0.04), frameon=False,\n           fontsize=8, handletextpad=0.4, ncol=2, columnspacing=1.2)\n\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![The two GNE scales, using the normative values of @godino2010gne at a 1000-Hz bandwidth. Left: the transform. Because GNEl is the logarithm of (1 − GNE), the curve steepens as GNE approaches 1, so a small change in GNE near the top of its range is a large change in GNEl. Right: the same three values placed on each ruler, both drawn so that a cleaner voice lies to the right. On GNE's nominal 0-to-1 scale the normal mean, the normal 95th percentile and the pathological mean fall within 0.031 of one another, close enough that they cannot be labelled separately; the same three values spread across 7.1 dB of GNEl. This is why a GNE value and a GNEl value cannot be compared without converting, and why the published norms are reported on the log scale.](gne_files/figure-html/fig-gne-scale-output-1.png){#fig-gne-scale width=800 height=385 fig-alt='Two panels. On the left, a curve of GNEl in decibels against GNE, falling steeply as GNE approaches 1, with three marked points. On the right, two horizontal rulers: on the upper GNE ruler the three points are crowded together at the far right end, while on the lower GNEl ruler the same three points are spread well apart, with connecting lines fanning out between the two rulers.'}\n:::\n:::\n\n\n## Normative data\n\nOne study publishes GNE normative values: means, standard deviations and\npercentiles for normal and pathological groups, separated by gender, from 226\ntalkers of the MEEI/Kay Elemetrics database (53 normal, 173 pathological),\nsustained /ah/ [@godino2010gne]. All values are **GNEl**; the right-hand column\nconverts the clinically actionable figure onto the raw GNE scale.\n\n| Group | Normal mean (GNEl) | Normal 95th pct (GNEl) | 95th pct as GNE |\n|---|---|---|---|\n| All | −21.28 (SD 2.31) | −17.92 | 0.9839 |\n| Female | −21.89 (SD 2.08) | −18.84 | 0.9869 |\n| Male | −20.34 (SD 2.37) | −17.44 | 0.9820 |\n\n: Normative values, bandwidth 1000 Hz, frequency shift 300 Hz [@godino2010gne]. Conversions computed for this reference; see `wiki/measures/gne.md`. {#tbl-gne-norms}\n\nThe pathological group averaged GNEl −14.17 (SD 3.31),\nwith a 5th percentile of −19.39 [@godino2010gne]. At a 3000-Hz bandwidth the\nnormal mean is −11.89 and the 95th percentile −7.33, a GNE of 0.8151\n[@godino2010gne] — the same voices, a different number, because the bandwidth\nis part of the measure.\n\nThe authors report **no significant difference between the genders** and state\nthat their database revealed no statistical evidence that the normative values\ndiffer for males and females, while still tabulating them separately\n[@godino2010gne]. Both facts belong together.\n\n::: {.callout-warning}\n**These are not Praat values.** They were computed with WPCVox, the authors'\nown application, whose version is not stated, at a window length of 60 ms\n[@godino2010gne]. They are the reference values that exist; they are not a\nnormal band for a Praat or PhonaLab measurement. See\n[Pipeline dependence](foundations-pipeline.qmd).\n:::\n\n## Published cutoffs\n\nCutoffs exist, and they do not all answer the same question. Two discriminate\nthe **presence of a voice disorder**; two discriminate a **perceptual\ndimension**. They must not be pooled or compared.\n\n| Measure | Discriminates | Cutoff | AUC | Sens. | Spec. | Pipeline | Class |\n|---|---|---|---|---|---|---|---|\n| GNE 2000 Hz | voice disorder | > 0.92 | 0.785 | 70.97% | 73.61% | Praat 6.2.10 + VoxMore v1.0.0, pt-BR, sustained [a] | pipeline-compatible |\n| GNE 1000 Hz | voice disorder | > 0.92 | 0.76 | 83.87% | 54.65% | as above | pipeline-compatible |\n| GNE 3000 Hz | voice disorder | > 0.9 | 0.76 | 64.52% | 82.16% | as above | pipeline-compatible |\n| GNEmax-4500 Hz | perceived breathiness | 0.89 | 0.886 | 91.7% | 74.3% | VOXplot on Praat algorithms, **no version stated**, German, sustained [a:] | unclassified (no software version) |\n| GNEmax-4500 Hz | perceived hoarseness | 0.91 | 0.798 | 88.9% | 62.3% | as above | unclassified (no software version) |\n\n: Published GNE cutoffs, with their compatibility class [@feliciano2026cutoffs; @barsties2023voxplot]. {#tbl-gne-cutoffs}\n\nThe first three come from 376 Brazilian Portuguese speakers, 277 with and 99\nwithout a voice disorder, against a reference standard combining\nvideolaryngostroboscopy with perceptual judgement [@feliciano2026cutoffs].\nThey are `pipeline-compatible` because the study states Praat 6.2.10 and the\nplugin's own source supplies the four arguments to `To Harmonicity (gne)`\n[@abreu2022voxmoreplugin] — so a reader running that pipeline can reproduce\nthem. Two qualifications: the study does not state which plugin build it ran,\nand **the class describes the row, not a licence.** A cutoff is\npipeline-compatible for the pipeline it names, not for yours.\n\nThe last two come from 218 German voice samples, by the Youden index, against\nperceptual ratings [@barsties2023voxplot]. They are `unclassified` because no\nsoftware version appears anywhere in that article — neither VOXplot's nor the\nPraat algorithms' underneath. That sample is also **not independent** of\nmaterial cited elsewhere in this reference: the recordings and perceptual\njudgements come from the German AVQI/ABI validation and have been re-analysed\nmore than once.\n\nNote from the table that GNE separated breathiness better than hoarseness in\nthe one study that tested both — AUC 0.886 against 0.798\n[@barsties2023voxplot], which is what a measure designed for breathiness\nshould do.\n\n## Confounds and cautions\n\n**No compatible reference exists for a Praat pipeline.** Every GNE reference\nvalue published to date was computed by something else: WPCVox for the norms,\nVOXplot without a stated version, VoxMore for the Brazilian cutoffs. Report a\nPraat GNE with its settings and state that no compatible reference exists,\nrather than borrowing one.\n\n**The bandwidth is not a setting.** Eight distinct GNE measures come from one\nscript by varying bandwidth and maximum frequency [@barsties2017abi], the\nbandwidth determines which percept the measure tracks [@barsties2018meta], and\nit changes the measure's dynamic range and its sensitivity to *f*~0~\n[@michaelis1997gne]. A value reported as \"GNE\" without its bandwidth and\nfrequency range is not comparable with anything.\n\n**Which bandwidth is best depends on the purpose, and the literature says so.**\nFor detecting disorder at all, screening accuracy peaked at a 1000-Hz bandwidth\n(AUC 0.97) and fell to 0.86 at 3000 Hz [@godino2010gne]. For the hoarseness\ndiagram, Michaelis and colleagues used 3000 Hz, because at that bandwidth GNE\ncorrelates least with jitter and shimmer and can therefore serve as an\nindependent axis. @godino2010gne address the conflict directly and conclude\nthat the choice depends on the intended use — 3000 Hz for an independent noise\naxis, 1000 Hz for screening, accepting that the narrower band integrates more\naperiodicity information. The mechanism both sides agree on: too narrow and\nsome filter channels carry no harmonic energy, too wide and the envelope\nestimate degrades [@godino2010gne].\n\n**Window length and frequency shift.** Screening accuracy was insensitive to\nwindow length across 30–500 ms, and 60 ms was chosen as a trade-off; frequency\nshift barely mattered, with AUC 0.97 at 100, 200 and 300 Hz alike\n[@godino2010gne]. Whether that study's \"frequency shift\" is Praat's `step`\nargument is **not established by any source cited here**: Praat's default step\nis 80 Hz and the study's choice is 300 Hz.\n\n**Recording conditions.** Environmental noise and software significantly affect\nGNE as well as the perturbation measures, though less substantially\n[@barsties2018meta].\n\n**Software version.** GNE is one of the ABI's two principal markers, and Praat\nversions running an identical script on identical recordings have produced\nmaterially different index values; see\n[Pipeline dependence](foundations-pipeline.qmd). No study tests GNE itself\nacross Praat versions.\n\n**Signal typing: promising, unproven.** GNE is claimed to be applicable even\nto highly irregular glottal oscillations [@michaelis1997gne], the mechanism\nsupports the claim, and the vocal-fry comparison is a worked case. But no\nstudy evaluates GNE against the Type 1–4 framework (see\n[Signal typing](foundations-signal-typing.qmd)), and one recording is not a\nvalidation. The perturbation argument for restricting analysis to Type 1\nsignals does not transfer to a measure that needs no *f*~0~ estimate — which\nis a reason to investigate, not a reason to assume.\n\n## Validation\n\nThe development paper [@michaelis1997gne] and its sequel\n[@michaelis1998features] establish the algorithm and the independence\nproperty on synthesized signals. @frohlich2000hoarseness puts GNE to clinical\nuse as the noise axis of the hoarseness diagram. @godino2010gne is the only\ndedicated evaluation of GNE as a standalone screening measure and the only\nsource of normative values. @feliciano2026cutoffs and @barsties2023voxplot\nsupply the modern cutoffs. The pooled perceptual correlations\n[@barsties2018meta] rest on two studies per percept and are descriptive\ncontext, not thresholds.\n\nWhat is still missing is a GNE reference computed with a stated, current,\nwidely used pipeline. Until one exists, this chapter publishes no GNE normal\nband.\n\n## Compute it in PhonaLab\n\n> **[Open PhonaLab →](https://phonalab.com)**\n>\n> GNE is reported as a component of the Acoustic Breathiness Index, where the\n> provenance belongs to the ABI cutoff for your language and task. PhonaLab\n> displays no GNE normal band, because no compatible reference exists.\n\n",
    "supporting": [
      "gne_files"
    ],
    "filters": [],
    "includes": {}
  }
}