{
  "hash": "7baa5e91a0d5226cb83f980deb8a59d9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Cepstral Peak Prominence (CPP and CPPS)\"\nexecute:\n  echo: true\njupyter: python3\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code for this figure\"\n---\n\n::: {.callout-note}\n**Living draft.** This chapter reflects the sources cited below and will be\nrevised as further sources are incorporated. Found an error? Use the *Report an\nissue* link in the sidebar.\n:::\n\n\n## Definition\n\n**The question cepstral peak prominence asks is how strongly a harmonic\npattern stands out from the background.** Unlike jitter and shimmer it never\nneeds to find where one cycle ends and the next begins, which is why it\nsurvives in voices where cycle-by-cycle measures do not.\n\nCepstral peak prominence (CPP) quantifies how strongly the harmonic structure\nof a voice signal emerges from its background. The cepstrum used in voice\nanalysis is obtained by transforming the waveform into a spectrum, taking the\nlogarithm, and transforming again; its horizontal axis is a time-like dimension\ncalled *quefrency* [@murton2020cpp]. The periodic harmonic peaks of the\nspectrum collapse into a single dominant cepstral peak at the quefrency of the\nvoice period. The height of that peak above a regression line through the whole\ncepstrum is the CPP, reported in decibels [@murton2020cpp]. The amplitude of\nthe dominant cepstral peak (the first *rahmonic*) reflects the strength with\nwhich the fundamental frequency emerges from competing background frequencies\n[@maryn2009cepstral].\n\nLower CPP values are associated with greater dysphonia severity\n[@murton2020cpp]. Two properties distinguish CPP from the classical\nperturbation measures. First, it can be extracted from connected speech as well\nas sustained vowels. Second, it does not require direct computation of the\nfundamental frequency, so no pitch detection or tracking is needed — which\nmakes cepstral measures robust in dysphonic and particularly in breathy voices,\nwhere period-by-period analysis breaks down [@murton2020cpp; @barsties2018meta].\nThe 2018 ASHA instrumental-assessment guidance recommended CPP as a general\nmeasure of dysphonia, replacing jitter, shimmer, and harmonics-to-noise ratio\nin that role [@murton2020cpp].\n\n## Computation\n\nThe waveform is Fourier-transformed into a spectrum, the logarithm of the\nspectrum is taken, and a second (inverse) Fourier transform carries the result\ninto the cepstral domain [@murton2020cpp]. A linear regression line relating\nquefrency to cepstral magnitude is fitted through the cepstrum, and CPP is the\ndifference in amplitude between the cepstral peak and the point on the\nregression line directly below it [@maryn2009cepstral; @barsties2018meta].\n\n**CPP versus CPPS.** Averaging the cepstrum first across time and then across\nquefrency yields a *smoothed* cepstrum; the same peak-minus-regression-line\nmeasurement on the smoothed cepstrum is the smoothed cepstral peak prominence,\nCPPS [@maryn2009cepstral]. Hillenbrand and colleagues developed SpeechTool, a\nprogram that derives the unsmoothed cepstrum; a later modification of the\nalgorithm, averaging across time and then across quefrency, produced the\nsmoothed cepstrum [@maryn2009cepstral].\n\n**Praat and SpeechTool CPPS are on different scales.** @maryn2015praat compared\nSpeechTool's original CPPS with Praat's implementation on a sustained vowel and\ncontinuous speech from 289 subjects with voice disorders. The two correlate\nalmost perfectly, but their numerical ranges differ by about 5 dB: mean CPPS was\n6.61 dB in SpeechTool against 11.66 dB in Praat, on the same recordings. The\nrelation between them is *y* = 1.4387*x* + 2.1543 with *r*² = 0.924. A cutoff\nobtained in one program cannot be applied to a value computed in the other\nwithout that conversion. The strength of the correlation means the two measure\nthe same thing; it does not make the numbers interchangeable. The corresponding\ncomparison for the index built on CPPS is much closer in scale: the Praat-only\nAVQI accounted for 96.0% of the variance of the SpeechTool-based AVQI, with\nmeans of 3.97 against 3.83 [@maryn2015praat].\n\n**Software implementations.** Three computation algorithms dominate the\nclinical literature: Hillenbrand and Houde's CPPS algorithm, Praat's CPPS\nalgorithm, and the CPP computation in Analysis of Dysphonia in Speech and Voice\n(ADSV, PENTAX Medical) [@murton2020cpp]. Their parameter choices differ in ways\nthat matter:\n\n- ADSV applies a voicing activity detector, and frames with negative CPP\n  (cepstral peak below the regression line) are excluded from analysis\n  [@murton2020cpp].\n- Praat computes CPPS from a PowerCepstrogram and includes no voicing activity\n  detection. The reference configuration used by @murton2020cpp: 60-Hz pitch\n  floor, 2-ms time step, 5-kHz maximum frequency, pre-emphasis from 50 Hz,\n  time averaging window 0.01 s, quefrency averaging window 0.001 s, peak\n  search range 60–330 Hz, parabolic interpolation, straight tilt line over the\n  quefrency range 0.001–0 s, robust fit.\n\nBecause of these differences, values from different programs live on different\nscales and are not interchangeable (see [Confounds and cautions]).\n\n\n@fig-cpp-measure follows one frame through all three domains: the waveform,\nthe comb of harmonics in its spectrum, the single cepstral peak the comb\ncollapses into, and the distance that is reported as CPP.\n\n::: {#cell-fig-cpp-measure .cell execution_count=2}\n``` {.python .cell-code}\nfs, f0 = 16000, 125.0\nT0 = 1.0 / f0\nncyc = 80\nrng = np.random.default_rng(2)\nper = T0 * (1 + 0.002 * rng.standard_normal(ncyc))\namp = 1 + 0.02 * rng.standard_normal(ncyc)\nx = vs.synth_vowel(per, amp, fs, noise_rel_db=-28, seed=9)\n\nL = int(0.040 * fs)\ni0 = len(x) // 2 - L // 2\nseg = x[i0:i0 + L] * np.hanning(L)\nnfft = 4096\nmag = np.abs(np.fft.rfft(seg, nfft)) + 1e-12\nfreq = np.fft.rfftfreq(nfft, 1 / fs)\nceps = np.fft.irfft(np.log(mag))\nq = np.arange(len(ceps)) / fs\n\nqlo, qhi = 1 / 400, 1 / 60\nfitsel = (q >= 0.001) & (q <= 0.015)\nline = np.polyval(np.polyfit(q[fitsel], ceps[fitsel], 1), q)\nsel = (q >= qlo) & (q <= qhi)\nipk = np.flatnonzero(sel)[np.argmax(ceps[sel])]\n\nfig, axes = plt.subplots(1, 3, figsize=(7.6, 2.9))\n\n# --- A: the waveform the frame is taken from\nax = axes[0]\ntt = np.arange(L) / fs\nraw = x[i0:i0 + L]\nax.plot(tt * 1e3, raw, color=vs.INK, lw=0.8)\npk = i0 + np.array([np.argmax(raw[:int(0.009 * fs)]),\n                    np.argmax(raw[int(0.009 * fs):int(0.018 * fs)]) + int(0.009 * fs)])\npt = (pk - i0) / fs\nax.annotate(\"\", xy=(pt[0] * 1e3, 1.12), xytext=(pt[1] * 1e3, 1.12),\n            arrowprops=dict(arrowstyle=\"<->\", color=vs.GREEN, lw=1.1, shrinkA=0, shrinkB=0))\nax.text(np.mean(pt) * 1e3, 1.18, \"one period, 8 ms\", ha=\"center\", va=\"bottom\",\n        fontsize=8, color=vs.GREEN)\nax.set_xlabel(\"Time (ms)\"); ax.set_ylabel(\"Pressure\")\nax.set_title(\"1 · Waveform\", color=vs.INK)\nax.set_ylim(-1.15, 1.5); ax.set_yticks([]); ax.set_xlim(0, 40)\nvs.style_axes(ax); ax.grid(False)\n\n# --- B: its log spectrum\nax = axes[1]\nk = freq <= 4000\ndB = 20 * np.log10(mag[k]); dB -= dB.max()\nax.plot(freq[k] / 1e3, dB, color=vs.BLUE, lw=0.8)\nax.set_xlabel(\"Frequency (kHz)\"); ax.set_ylabel(\"Level (dB, relative)\")\nax.set_title(\"2 · Log spectrum\", color=vs.INK)\nax.set_xlim(0, 4); ax.set_ylim(-70, 8)\nvs.style_axes(ax)\nax.annotate(\"harmonics every $F_0$\", xy=(0.62, -10), xytext=(1.25, 4),\n            fontsize=7.5, color=vs.INK,\n            arrowprops=dict(arrowstyle=\"->\", color=vs.MUTED, lw=0.9))\n\n# --- C: the cepstrum, and the measurement\nax = axes[2]\nkk = (q >= 0.0012) & (q <= 0.016)\nax.plot(q[kk] * 1e3, ceps[kk], color=vs.INK, lw=0.9)\nax.plot(q[kk] * 1e3, line[kk], color=vs.ORANGE, lw=1.3, ls=\"--\")\nax.plot([q[ipk] * 1e3] * 2, [line[ipk], ceps[ipk]], color=vs.GREEN, lw=2.4,\n        solid_capstyle=\"butt\", zorder=4)\nax.plot(q[ipk] * 1e3, ceps[ipk], marker=\"o\", ms=5, color=vs.GREEN,\n        mfc=\"white\", mec=vs.GREEN, mew=1.6, zorder=5)\nax.annotate(\"CPP\", xy=(q[ipk] * 1e3, (line[ipk] + ceps[ipk]) / 2),\n            xytext=(q[ipk] * 1e3 + 2.0, (line[ipk] + ceps[ipk]) / 2),\n            fontsize=9, color=vs.INK, va=\"center\", fontweight=\"bold\",\n            arrowprops=dict(arrowstyle=\"->\", color=vs.GREEN, lw=1.2))\nax.text(q[ipk] * 1e3, ceps[ipk] + 0.015, f\"{q[ipk]*1e3:.1f} ms\",\n        ha=\"center\", va=\"bottom\", fontsize=8, color=vs.INK)\nax.text(0.97, 0.03, \"dashed: regression\\nthrough the cepstrum\",\n        transform=ax.transAxes, ha=\"right\", va=\"bottom\", fontsize=7.5,\n        color=vs.ORANGE, linespacing=1.3)\nax.set_xlabel(\"Quefrency (ms)\"); ax.set_ylabel(\"Cepstral magnitude\")\nax.set_title(\"3 · Cepstrum\", color=vs.INK)\nax.set_xlim(0, 16)\npad = 0.18 * (ceps[kk].max() - ceps[kk].min())\nax.set_ylim(ceps[kk].min() - pad, ceps[kk].max() + 2.6 * pad)\nvs.style_axes(ax)\n\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![What the measurement is, on one 40-ms frame of a synthetic vowel (F0 = 125 Hz). **1** the waveform, repeating every 8 ms. **2** its log spectrum, a comb of harmonics spaced by F0. **3** the cepstrum of that spectrum, in which the whole comb collapses into a single peak at a quefrency of 8.0 ms — the voice period, and the reciprocal of 125 Hz. CPP is the vertical distance from that peak to the regression line fitted through the cepstrum, marked in green. The near-zero quefrency region, which carries the spectral envelope rather than the harmonic spacing, is outside the plotted range. The vertical scale in panel 3 is cepstral magnitude in log units; programs report CPP in decibels. The three domains are treated generally in [Signal Fundamentals](foundations-signal.qmd). Signal is synthetic and illustrative.](cpps_files/figure-html/fig-cpp-measure-output-1.png){#fig-cpp-measure width=826 height=308 fig-alt='Three panels left to right. The first is a vowel waveform with one period marked as 8 milliseconds. The second is a spectrum with evenly spaced harmonic peaks falling away with frequency. The third is a mostly flat cepstrum with one tall narrow peak at 8 milliseconds, a dashed regression line through the baseline, and a green bar marking the height of the peak above that line, labelled CPP.'}\n:::\n:::\n\n\n## What it captures\n\nCPP behaves as a general index of overall dysphonia severity. In the\nMassachusetts Eye and Ear Infirmary (MEEI) data of @murton2020cpp, CPP values\nbelow task- and software-specific cutoffs indicated the presence of a voice\ndisorder with up to 94.5% accuracy, and ADSV CPP estimated mean listener\nratings of overall severity with *r*² from .5 to .74 depending on task (Praat\nCPPS: *r*² from .38 to .72). Regression lines allow a severity estimate from\nCPP; a Praat CPPS of 10 dB on sustained /a/ predicts a CAPE-V overall severity\nof approximately 54 [@murton2020cpp].\n\nMeta-analytically, CPP and CPPS are the best acoustic predictors of\n**breathiness**, and the only acoustic markers that reached the validity\ncriterion for breathiness in both sustained vowels and continuous speech\n[@barsties2018meta]. Pooled effect sizes:\n\n| Perceptual dimension | Task | Measure | Weighted *r* | N |\n|---|---|---|---|---|\n| Breathiness | sustained vowel | CPP | .66 | 468 |\n| Breathiness | continuous speech | CPP | .73 | 98 |\n| Breathiness | sustained vowel | CPPS | .64 | 133 |\n| Breathiness | continuous speech | CPPS | .63 | 242 |\n| Roughness | continuous speech | CPPS | .60 | 217 |\n\n: Pooled meta-analytic correlations with perceptual ratings [@barsties2018meta]. {#tbl-cpp-meta}\n\nFor **roughness**, CPPS reached the acceptability criterion only in continuous\nspeech, where it was the only adequate predictor; CPPS does not, however,\nseem to distinguish the subtypes roughness and breathiness from each other\nwell [@barsties2018meta]. Although the cepstral measures were originally designed\nfor breathiness, they proved to be the most accurate acoustic measures of\noverall dysphonia severity [@barsties2018meta].\n\nIn severely aperiodic and alaryngeal voices, where perturbation measures fail\nfor lack of a reliably detectable fundamental period, CPP remains computable:\nin tracheoesophageal speakers it was the strongest single acoustic correlate of\noverall voice quality (*r~s~* = .78, about 60% of variance explained), and a\ntwo-factor regression combining CPP with the height of the second spectral\nharmonic reached *r~s~* = .87 with listener rankings [@maryn2009cepstral]. That\nmultivariate strategy is the same one the [AVQI](avqi.qmd) applies to laryngeal\nvoice.\n\n## Normative data\n\nCPP values and cutoffs belong to the pipeline that produced them: the program,\nits version and settings, and the speech material. Each row below states its\npipeline and its compatibility class; see\n[Pipeline Dependence and Reference Values](foundations-pipeline.qmd) for the\nclasses. Compare a measured value only with a row whose pipeline matches.\n\n| Population | Task | Pipeline | Cutoff | Accuracy | Class |\n|---|---|---|---|---|---|\n| MEEI, English; 295 patients, 50 controls | Sustained /a/ | ADSV 3.4.2 CPP, default settings | 11.46 dB | 79.4% | pipeline-compatible |\n| MEEI, English; 291 patients, 50 controls | Rainbow Passage, first 12 s | ADSV 3.4.2 CPP, default settings | 6.11 dB | 87.7% | pipeline-compatible |\n| MEEI, English; 295 patients, 50 controls | Sustained /a/ | Praat 6.0.40 CPPS, Watts et al. settings | 14.45 dB | 77.4% | pipeline-compatible |\n| MEEI, English; 291 patients, 50 controls | Rainbow Passage, first 12 s | Praat 6.0.40 CPPS, Watts et al. settings | 9.33 dB | 94.5% | pipeline-compatible |\n| English; 100 voice-disordered, 70 controls | Rainbow Passage, second sentence | Praat 6.0.17 CPPS, factory settings | 19.10 dB | AUC 0.91 | pipeline-compatible |\n| — | Sustained /i/ | — | No published cutoff in the sources reviewed | — | — |\n\n: Diagnostic cutoffs (voice disorder vs. typical voice). MEEI rows: @murton2020cpp. Second-sentence rows: @sauder2017cpps. Sustained /i/: @buckley2023cpp. {#tbl-cpp-cutoffs}\n\nOther reported cutoffs are listed below for context only. Their pipelines\nare incomplete where they are reported: no software version, or values read\nfrom another paper's summary table. They are not used as cutoffs here.\n\n| Study | Language | Pipeline | Sustained vowel | Running speech | Class |\n|---|---|---|---|---|---|\n| Sauder et al. 2017 | English | ADSV CPPS, factory settings; ADSV version not stated | — | 5.53 dB (second sentence of the Rainbow Passage; AUC 0.81) | unclassified (no software version) |\n| Heman-Ackah et al. 2003 | English | CPPS (Hillenbrand) | 10 dB | 5 dB | unclassified (as tabulated by Murton et al.) |\n| Heman-Ackah et al. 2014 | English | CPPS (Hillenbrand) | — | 4.0 dB | unclassified (as tabulated by Murton et al.) |\n| Yu et al. 2018 | Korean | ADSV CPP | 12 dB | 7 dB | unclassified (as tabulated by Murton et al.) |\n| Delgado-Hernández et al. 2019 | Spanish | Praat CPPS (AVQI configuration) | 13.96 dB | 8.37 dB | unclassified (as tabulated by Murton et al.) |\n\n: Reported cutoffs without a complete pipeline, shown as history. Normal vs. dysphonic except Heman-Ackah 2003 (mild vs. severe). Sauder row: @sauder2017cpps; other rows as tabulated by @murton2020cpp. {#tbl-cpp-prior}\n\nThe two Hillenbrand rows show why the class matters. Their running-speech\nvalues, 5 dB and 4.0 dB, are not low versions of the Praat values elsewhere in\nthis chapter; they sit on the SpeechTool scale, about 5 dB below Praat's for the\nsame recordings [@maryn2015praat]. Converted with the published relation, 4.0 dB\nis roughly 1.3 dB on the Praat scale, far outside the range of any Praat cutoff\nhere. Rather than convert second-hand values whose task and settings are only\npartly stated, this reference leaves them as history. The ADSV rows are a\nseparate matter: they are unclassified because no ADSV version is stated where\nthe values are reported [@murton2020cpp].\n\n@buckley2023cpp measured 150 speakers without voice disorders, aged 18–91\nyears, and proposed normative lower limits at 2 SD below the group mean.\nPraat CPPS used the Watts et al. settings (version 6.0.50); ADSV used default\nsettings except a CPP threshold of 1 dB and vocalic event detection.\n\n| Task | Pipeline | Males | Females | Class |\n|---|---|---|---|---|\n| Sustained /a/, middle 1 s | Praat 6.0.50 CPPS, Watts et al. settings | 11.72 dB | 11.05 dB | pipeline-compatible |\n| Sustained /i/, middle 1 s | Praat 6.0.50 CPPS, Watts et al. settings | 12.01 dB | 10.37 dB | pipeline-compatible |\n| Rainbow Passage, sentences 2–3 | Praat 6.0.50 CPPS, Watts et al. settings | 6.40 dB | 6.49 dB | pipeline-compatible |\n| Sustained /a/, middle 1 s | ADSV CPP; version not stated | 8.86 dB | 8.09 dB | unclassified (no software version) |\n| Sustained /i/, middle 1 s | ADSV CPP; version not stated | 6.68 dB | 4.65 dB | unclassified (no software version) |\n| Rainbow Passage, sentences 2–3 | ADSV CPP; version not stated | 5.40 dB | 5.04 dB | unclassified (no software version) |\n\n: Normative lower limits for typical speakers [@buckley2023cpp]. The ADSV rows are shown for comparison with the Praat rows; the ADSV version is not stated, so they are not used as reference limits. {#tbl-cpp-norms}\n\nIn that sample, 56% of females and 65.3% of males fell below the 9.33-dB Praat\ncutoff for the Rainbow Passage, and all fell below the 19.10-dB Praat cutoff\n[@buckley2023cpp].\n\n**Thresholds depend on software, settings and task.** Different algorithms\nproduce CPP values in different ranges, and thresholds are lower for\ncontinuous speech than for sustained vowels [@murton2020cpp]. On the same\nsamples, ADSV and Praat values correlate highly (*r* = 0.88), but their\nabsolute values cannot be compared directly [@sauder2017cpps].\n\n## Confounds and cautions\n\n**Software non-interchangeability.** On the same MEEI recordings, the\nsustained-vowel cutoff was 11.46 dB for ADSV and 14.45 dB for Praat. The\nalgorithms can also diverge qualitatively: one speaker measured 11.7 dB in\nPraat CPPS but 3.5 dB in ADSV CPP, with phonation showing irregular, widely\nspaced pulses perceived as strain and vocal fry [@murton2020cpp].\n\n**Task effects.** CPP thresholds are consistently lower for continuous speech\nthan for sustained vowels. CPP varies widely between different sentences; one\npossible explanation is their differing amounts of voicing. Comparisons within\nor between speakers must therefore use the same speech material. The results\nsuggest that including unvoiced frames in the average can artificially lower\nthe CPP of consonant-heavy material [@murton2020cpp].\n\n**Aphonia and voicing detection.** Where aphonic segments are included, a low\naverage CPP meaningfully reflects the aphonic quality — but very accurate\nvoicing detection can paradoxically produce a higher-than-expected CPP in\nintermittent aphonia, because only the periodic voiced fragments enter the\naverage [@murton2020cpp].\n\n**No established upper bound.** @murton2020cpp note that it is conceivable\nthat some voice disorders lead to abnormally *high* CPP, which a single\nthreshold would not take into account. They cite Awan and Awan (2020), who\nindicated that rough voices with a strong subharmonic component may exhibit\nhigh CPP values.\n\n**Vowel, loudness, sex, and age.** Awan et al. (2012), as cited by\n@murton2020cpp, found that low vowels such as /a/ tended to have higher CPP\nthan high vowels such as /i/, and that CPP increases significantly with\nloudness. Murton et al. attribute the loudness effect to increased glottal\nclosure and reduced perturbation, not to a change in underlying dysphonia.\nMale speakers tended to\nhave higher CPP than female speakers, possibly through loudness. The MEEI\ncontrols were 22–59 years old; separate norms for older adults may be needed\n[@murton2020cpp].\n\n**Cutoff vicinity.** Published cutoffs are one possible estimate; values near a\ncutoff deserve further consideration rather than a binary reading\n[@murton2020cpp].\n\n**Recording conditions.** Hardware, microphone placement, environmental noise,\nand software are known to affect perturbation measures; their impact on CPP and\nCPPS remains unclear and needs further investigation [@barsties2018meta].\n\n## Validation\n\nThe MEEI cutoff study [@murton2020cpp] and the roughness/breathiness\nmeta-analysis [@barsties2018meta] anchor the evidence summarized above. The\nmeta-analytic sustained-vowel breathiness effect sizes for CPP and CPPS pooled\nheterogeneous *r*-values; the authors retained these measures because they had\nthe highest study counts and sample sizes [@barsties2018meta]. The\ntracheoesophageal findings of @maryn2009cepstral extend the measure's validity\nto alaryngeal voice.\n\n## Compute it in PhonaLab\n\n> **[Open PhonaLab →](https://phonalab.com)**\n>\n> *PhonaLab is developed by the author of this reference; see\n> [Competing interests](intro.qmd#competing-interests).*\n>\n> Upload a sustained vowel or a reading passage and compute CPPS on your own\n> recording, with the software and task always reported alongside the value.\n\n",
    "supporting": [
      "cpps_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}