<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Acoustic Breathiness Index (ABI) – Acoustic Measures of Voice Quality</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./release-notes.html" rel="next">
<link href="./avqi.html" rel="prev">
<link href="./favicon.svg" rel="icon" type="image/svg+xml">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5c01c0ce2b51dbeda25ce515ef8205e7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Cloudflare Web Analytics --><script type="module" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;: &quot;b81dffd01ef647da838f61336a77571c&quot;}"></script><!-- End Cloudflare Web Analytics -->

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./avqi.html">Part IV — Composite Indices</a></li><li class="breadcrumb-item"><a href="./abi.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Acoustic Breathiness Index (ABI)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Acoustic Measures of Voice Quality</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/LuceroJC/voice-measures" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-signal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Signal Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-signal-typing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Signal Typing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-pipeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Pipeline Dependence and Reference Values</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II — Periodicity and Stability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./jitter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Jitter (Frequency Perturbation)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./shimmer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Shimmer (Amplitude Perturbation)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Noise and Harmonic Structure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./hnr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Harmonic-to-Noise Ratio (HNR)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cpps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Cepstral Peak Prominence (CPP and CPPS)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Composite Indices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./avqi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Acoustic Voice Quality Index (AVQI)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Acoustic Breathiness Index (ABI)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Back matter</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./release-notes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Release notes and errata</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#definition" id="toc-definition" class="nav-link active" data-scroll-target="#definition"><span class="header-section-number">10.1</span> Definition</a></li>
  <li><a href="#computation" id="toc-computation" class="nav-link" data-scroll-target="#computation"><span class="header-section-number">10.2</span> Computation</a></li>
  <li><a href="#what-it-captures" id="toc-what-it-captures" class="nav-link" data-scroll-target="#what-it-captures"><span class="header-section-number">10.3</span> What it captures</a></li>
  <li><a href="#normative-data" id="toc-normative-data" class="nav-link" data-scroll-target="#normative-data"><span class="header-section-number">10.4</span> Normative data</a></li>
  <li><a href="#confounds-and-cautions" id="toc-confounds-and-cautions" class="nav-link" data-scroll-target="#confounds-and-cautions"><span class="header-section-number">10.5</span> Confounds and cautions</a></li>
  <li><a href="#validation" id="toc-validation" class="nav-link" data-scroll-target="#validation"><span class="header-section-number">10.6</span> Validation</a></li>
  <li><a href="#compute-it-in-phonalab" id="toc-compute-it-in-phonalab" class="nav-link" data-scroll-target="#compute-it-in-phonalab"><span class="header-section-number">10.7</span> Compute it in PhonaLab</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/LuceroJC/voice-measures/edit/main/abi.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/LuceroJC/voice-measures/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./avqi.html">Part IV — Composite Indices</a></li><li class="breadcrumb-item"><a href="./abi.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Acoustic Breathiness Index (ABI)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Acoustic Breathiness Index (ABI)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Living draft.</strong> This chapter reflects the sources cited below and will be revised as further sources are incorporated. Found an error? Use the <em>Report an issue</em> link in the sidebar.</p>
</div>
</div>
<section id="definition" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="definition"><span class="header-section-number">10.1</span> Definition</h2>
<p><strong>The question the ABI asks is how breathy the voice sounds.</strong> Like the AVQI it combines several acoustic markers into a single score, but it is aimed at one perceptual dimension rather than at overall severity.</p>
<p>The Acoustic Breathiness Index (ABI) is a multiparametric, nine-variable acoustic measure that quantifies the degree of perceived breathiness with a single score, computed from concatenated samples of continuous speech and the sustained vowel /a/ <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. Its perceptual target is breathiness: turbulent noise, excessively high in frequency, resulting from air leakage during incomplete glottal closure <span class="citation" data-cites="barsties2021abi delgado2018avqi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>; <a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. Both speech tasks contribute three seconds of voiced material each, a design chosen for ecological validity <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. The index was first published in 2017 for a Dutch-speaking population <span class="citation" data-cites="barsties2017abi barsties2021abi">(<a href="#ref-barsties2017abi" role="doc-biblioref">Barsties v. Latoszek et al. 2017</a>, <a href="#ref-barsties2021abi" role="doc-biblioref">2021</a>)</span>.</p>
<p>Where the <a href="./avqi.html">AVQI</a> targets <em>overall</em> voice quality, the ABI isolates one perceptual dimension. The two indices share the concatenation protocol and several components.</p>
</section>
<section id="computation" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="computation"><span class="header-section-number">10.2</span> Computation</h2>
<p>The ABI contains nine parameters <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>:</p>
<div id="tbl-abi-components" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-abi-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.1: The nine ABI components <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.
</figcaption>
<div aria-describedby="tbl-abi-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Abbreviation</th>
<th>What it measures</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smoothed cepstral peak prominence</td>
<td>CPPS</td>
<td>Height of the first rahmonic’s peak over the regression line through the smoothed cepstrum — see the <a href="./cpps.html">CPPS chapter</a></td>
</tr>
<tr class="even">
<td>Jitter local</td>
<td>Jit</td>
<td>Average difference between successive periods, divided by the average period</td>
</tr>
<tr class="odd">
<td>Glottal-to-noise excitation ratio</td>
<td>GNEmax-4500 Hz</td>
<td>Excitation due to vocal-fold oscillation versus excitation by turbulent noise; reliable even under strong amplitude and frequency perturbations</td>
</tr>
<tr class="even">
<td>High-frequency noise</td>
<td>Hfno-6000 Hz</td>
<td>Relative level of high-frequency noise between the energy from 0–6 kHz and from 6–10 kHz</td>
</tr>
<tr class="odd">
<td>Harmonics-to-noise ratio of Dejonckere</td>
<td>HNR-D</td>
<td>Harmonic emergence of the spectral display in the 500–1500 Hz band</td>
</tr>
<tr class="even">
<td>Amplitude difference of the first two harmonics</td>
<td>H1–H2</td>
<td>Indirect measure of the relative length of the open phase of glottal oscillation; H1 is relatively high in breathy voices</td>
</tr>
<tr class="odd">
<td>Shimmer local dB</td>
<td>ShdB</td>
<td>Base-10 logarithm of the difference between amplitudes of successive periods, × 20</td>
</tr>
<tr class="even">
<td>Shimmer local</td>
<td>Shim</td>
<td>Absolute mean difference between amplitudes of successive periods, divided by the average amplitude</td>
</tr>
<tr class="odd">
<td>Period standard deviation</td>
<td>PSD</td>
<td>Variation in the standard deviation of periods</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The rescaled regression equation, as published in the development study <span class="citation" data-cites="barsties2017abi">(<a href="#ref-barsties2017abi" role="doc-biblioref">Barsties v. Latoszek et al. 2017</a>)</span>:</p>
<p><span class="math display">\[
\begin{aligned}
\text{ABI} = \bigl(5.0447730915 &amp;- 0.172\,\text{CPPS} - 0.193\,\text{Jit}
- 1.283\,\text{GNE}_{\max\text{-}4500}\\
&amp;- 0.396\,\text{Hfno}_{6000} + 0.01\,\text{HNR-D} + 0.017\,(\text{H1–H2})\\
&amp;+ 1.473\,\text{ShdB} - 0.088\,\text{Shim}
- 68.295\,\text{PSD}\bigr) \times 2.9257400394
\end{aligned}
\]</span></p>
<p>The German validation uses the same intercept <span class="citation" data-cites="barsties2020german">(<a href="#ref-barsties2020german" role="doc-biblioref">Barsties v. Latoszek et al. 2020</a>)</span>; the Spanish and US English validations print 5.0447740915 <span class="citation" data-cites="delgado2018avqi castillo2023avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>; <a href="#ref-castillo2023avqi" role="doc-biblioref">Castillo-Allendes et al. 2023</a>)</span>. The difference changes a score by about 3 × 10<sup>−6</sup> and has no clinical effect.</p>
<p>The score ranges from 0 to 10; the higher the ABI, the more severe the breathiness <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
<p>The development paper provides its Praat script as supplementary data <span class="citation" data-cites="barsties2017abi">(<a href="#ref-barsties2017abi" role="doc-biblioref">Barsties v. Latoszek et al. 2017</a>)</span>; this script is the reference implementation of the equation above. Later work refers to it as ABI script v. 01.01 <span class="citation" data-cites="stappenbeck2020praat">(<a href="#ref-stappenbeck2020praat" role="doc-biblioref">Stappenbeck et al. 2020</a>)</span>.</p>
<p>Signal processing uses Praat with the customised ABI script <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. Analysis applies only to voiced segments of the continuous speech, extracted with an automated Praat detection script, with a three-second /a/ segment appended <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. The continuous-speech part is standardised to a language-specific syllable count yielding three seconds of voiced speech. The Spanish validation set 33 syllables for both AVQIv3 and ABI; the 34-syllable (Dutch) and 30-syllable (Japanese) cut-offs it cites were established for AVQIv3 <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.</p>
</section>
<section id="what-it-captures" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="what-it-captures"><span class="header-section-number">10.3</span> What it captures</h2>
<p>ABI scores correlate strongly with auditory-perceptual breathiness ratings: Spearman <em>r<sub>s</sub></em> ranged from 0.746 to 0.890 across the six validation studies pooled in the meta-analysis <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. In Spanish, <em>r<sub>s</sub></em> = 0.826, with ABI accounting for 68.2% of the variance in mean breathiness ratings <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>; in the original Dutch study, <em>r<sub>s</sub></em> = 0.840 <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.</p>
<p>Unlike the CSID and AVQI, which assess overall voice quality, the ABI is particularly suitable for evaluating breathy voices — for example benign vocal-fold lesions dominantly characterised by breathiness (nodules of medium or large size), paralysis or paresis of the recurrent laryngeal nerve, and vocal-fold bowing associated with presbyphonia <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>; acute laryngitis also belongs to this group <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. Neither age and gender nor roughness significantly affects ABI in natural voices, and the index signals therapy-related voice quality changes with high sensitivity <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
<p>Independent meta-analysis of single measures supports the component choice: Hfno, H1–H2, HNR of Dejonckere, CPP, and CPPS all sit among the strongest single correlates of perceived breathiness, and only 12 of 85 acoustic measures predicted breathiness on sustained vowels with a weighted mean <em>r</em> of at least .60 <span class="citation" data-cites="barsties2018meta">(<a href="#ref-barsties2018meta" role="doc-biblioref">Barsties v. Latoszek et al. 2018</a>)</span>.</p>
</section>
<section id="normative-data" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="normative-data"><span class="header-section-number">10.4</span> Normative data</h2>
<p>ABI validation evidence applies to Praat with the customised ABI script <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. Each row states its pipeline and compatibility class; see <a href="./foundations-pipeline.html">Pipeline Dependence and Reference Values</a>.</p>
<div id="tbl-abi-thresholds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-abi-thresholds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.2: ABI diagnostic thresholds. Dutch: <span class="citation" data-cites="barsties2017abi">Barsties v. Latoszek et al. (<a href="#ref-barsties2017abi" role="doc-biblioref">2017</a>)</span>; Spanish: <span class="citation" data-cites="delgado2018avqi">Delgado Hernández et al. (<a href="#ref-delgado2018avqi" role="doc-biblioref">2018</a>)</span>; German: <span class="citation" data-cites="barsties2020german">Barsties v. Latoszek et al. (<a href="#ref-barsties2020german" role="doc-biblioref">2020</a>)</span>; Brazilian Portuguese: <span class="citation" data-cites="englert2020material">Englert et al. (<a href="#ref-englert2020material" role="doc-biblioref">2020</a>)</span> (counting 1–11 and reading text) and <span class="citation" data-cites="englert2019abstract">Englert et al. (<a href="#ref-englert2019abstract" role="doc-biblioref">2019</a>)</span> (counting 1–20); Japanese: <span class="citation" data-cites="hosokawa2019abi">Hosokawa et al. (<a href="#ref-hosokawa2019abi" role="doc-biblioref">2019</a>)</span>; Malayalam and Kannada: <span class="citation" data-cites="jayakumar2024abi">Jayakumar and Benoy (<a href="#ref-jayakumar2024abi" role="doc-biblioref">2024</a>)</span>; Persian: <span class="citation" data-cites="aghajanzadeh2025persian">Aghajanzadeh et al. (<a href="#ref-aghajanzadeh2025persian" role="doc-biblioref">2025</a>)</span>; US English: <span class="citation" data-cites="castillo2023avqi">Castillo-Allendes et al. (<a href="#ref-castillo2023avqi" role="doc-biblioref">2023</a>)</span>; Finnish: <span class="citation" data-cites="kankare2023abi">Kankare and Laukkanen (<a href="#ref-kankare2023abi" role="doc-biblioref">2023</a>)</span>; pooled: <span class="citation" data-cites="barsties2021abi">Barsties v. Latoszek et al. (<a href="#ref-barsties2021abi" role="doc-biblioref">2021</a>)</span>. Praat versions for the Spanish and German rows are those cited in each paper’s reference list. The Brazilian Portuguese counting 1–20 row reports diagnostic accuracy as a percentage (85.2%); it is shown here as AUC.
</figcaption>
<div aria-describedby="tbl-abi-thresholds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Population / language</th>
<th>Pipeline</th>
<th>Threshold</th>
<th>Sensitivity</th>
<th>Specificity</th>
<th>AUC</th>
<th>Class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dutch, development study (970 dysphonic, 88 healthy)</td>
<td>Praat 5.3.57, custom ABI script</td>
<td>3.44</td>
<td>82.4%</td>
<td>92.9%</td>
<td>0.948</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Spanish (136 dysphonic, 47 healthy)</td>
<td>Praat 6.0.22, ABI script</td>
<td>3.40</td>
<td>73.7%</td>
<td>95.4%</td>
<td>0.921</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>German (175 dysphonic, 43 healthy)</td>
<td>Praat 5.3.57, ABI script</td>
<td>3.42</td>
<td>72%</td>
<td>95%</td>
<td>0.91</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Brazilian Portuguese, counting 1–11 (40 dysphonic, 13 healthy; 17 syllables)</td>
<td>Praat 6.0.06, ABI script</td>
<td>2.38</td>
<td>95.2%</td>
<td>81.8%</td>
<td>0.924</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>Brazilian Portuguese, reading text (same 53 speakers; 32 syllables)</td>
<td>Praat 6.0.06, ABI script</td>
<td>3.13</td>
<td>88.1%</td>
<td>90.9%</td>
<td>0.929</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Brazilian Portuguese, counting 1–20 (113 dysphonic, 37 healthy; 37 syllables)</td>
<td>Praat version not stated; AKG C420 head-mounted microphone, per the meta-analysis table</td>
<td>2.94</td>
<td>75.3%</td>
<td>93.4%</td>
<td>0.852</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>US English (148 with voice disorders, 49 non-clinic-seeking; 22 syllables)</td>
<td>VOXplot 2.0.0; Praat 6.3.06 for extraction</td>
<td>2.35</td>
<td>84%</td>
<td>81%</td>
<td>0.89</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Finnish (108 dysphonic, 87 non-dysphonic; 31 syllables)</td>
<td>VOXplot 2.0.0; recorded in Praat 6.2.23</td>
<td>2.68</td>
<td>80%</td>
<td>80%</td>
<td>0.886</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>Japanese (288 dysphonic, 55 normophonic; 30 syllables + sustained vowel)</td>
<td>Praat 6.0.20, ABI script</td>
<td>3.44</td>
<td>76.3%</td>
<td>94.1%</td>
<td>0.939</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Malayalam and Kannada (91 normophonic, 69 dysphonic; 29 syllables in Malayalam, 25 in Kannada)</td>
<td>Praat 6.1.42, ABI script</td>
<td>3.66</td>
<td>61.73%</td>
<td>94.94%</td>
<td>0.816</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>Persian (136 dysphonic, 45 vocally healthy; 20 syllables, durations balanced)</td>
<td>VOXplot, version not stated</td>
<td>2.97</td>
<td>70%</td>
<td>87%</td>
<td>0.826</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Pooled, six studies (context only)</td>
<td>Praat + ABI script; heterogeneous hardware</td>
<td>none</td>
<td>0.84 (95% CI 0.83–0.85)</td>
<td>0.92 (95% CI 0.89–0.94)</td>
<td>0.94 (SROC)</td>
<td>meta-analytic</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The six validation studies pooled by the meta-analysis cover Dutch, German, Spanish, Brazilian Portuguese, Korean, and Japanese — four language groups — over 467 vocally healthy and 3136 voice-disordered subjects <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. The meta-analysis also derived a weighted threshold of 3.40 across its six studies (sensitivity 0.86, specificity 0.90) <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. This reference does not use it as a cutoff: a pooled value mixes languages, recording set-ups and Praat versions, and pooled sensitivity was highly heterogeneous (<em>I</em>² = 89.7%) <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. Use the row for the patient’s language and task.</p>
<p><a href="#tbl-abi-languages" class="quarto-xref">Table&nbsp;<span>10.3</span></a> lists the threshold each study reported.</p>
<div id="tbl-abi-languages" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-abi-languages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10.3: ABI thresholds by language, as tabulated in the meta-analysis <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>, Table 1, p.&nbsp;36)</span>. Study names are as cited there. All used Praat with the ABI script, an inclusion criterion of the meta-analysis; the Praat version is not stated in that table, and the values are second-hand, as cited there. <span class="math inline">\(r_s\)</span> is Spearman’s correlation between ABI and auditory-perceptual breathiness ratings.
</figcaption>
<div aria-describedby="tbl-abi-languages-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Language</th>
<th>Study</th>
<th>Healthy (N)</th>
<th>Disordered (P)</th>
<th>Concurrent validity (<span class="math inline">\(r_s\)</span>)</th>
<th>Threshold</th>
<th>Class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dutch</td>
<td>Barsties v. Latoszek et al.</td>
<td>88</td>
<td>954</td>
<td>0.840</td>
<td>3.44</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Spanish</td>
<td>Delgado Hernández et al.</td>
<td>47</td>
<td>136</td>
<td>0.826</td>
<td>3.40</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>Japanese</td>
<td>Hosokawa et al.</td>
<td>55</td>
<td>288</td>
<td>0.890</td>
<td>3.44</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Brazilian Portuguese</td>
<td>Englert et al.</td>
<td>37</td>
<td>113</td>
<td>0.746</td>
<td>2.94</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>German</td>
<td>Barsties v. Latoszek et al.</td>
<td>43</td>
<td>175</td>
<td>0.850</td>
<td>3.42</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Korean</td>
<td>Kim et al.</td>
<td>197</td>
<td>1470</td>
<td>0.870</td>
<td>3.69</td>
<td>language-conditional</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Thresholds range from 2.94 (Brazilian Portuguese) to 3.69 (Korean); see <em>Language dependence of the threshold</em> below. The later US English validation, not part of the meta-analysis, reports 2.35 (LR+ 4.29, LR− 0.2) and <span class="math inline">\(r_s\)</span> = 0.77 between ABI and perceived breathiness <span class="citation" data-cites="castillo2023avqi">(<a href="#ref-castillo2023avqi" role="doc-biblioref">Castillo-Allendes et al. 2023</a>)</span>. Its Methods define the ROC groups by the overall grade G for both indices, while its figure caption describes the ABI curve as separating breathy from nonbreathy voices, so the perceptual reference for the ABI threshold is not fully clear. The Finnish validation, also later than the meta-analysis, reports 2.68 (LR+ 4.00, LR− 0.25) and <span class="math inline">\(r_s\)</span> = 0.823 with perceived breathiness, with nonbreathy voices defined as mean B below 0.5 <span class="citation" data-cites="kankare2023abi">(<a href="#ref-kankare2023abi" role="doc-biblioref">Kankare and Laukkanen 2023</a>)</span>. The Brazilian Portuguese value comes from a congress abstract <span class="citation" data-cites="englert2019abstract">(<a href="#ref-englert2019abstract" role="doc-biblioref">Englert et al. 2019</a>)</span>. The meta-analysis cites it as a one-page 2019 item in the <em>International Archives of Otorhinolaryngology</em> (vol.&nbsp;23, p.&nbsp;106) <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. That citation does not resolve: the annals of the 18th Congress of the Otorhinolaryngology Foundation carry the journal’s branding and S-prefixed pages, and the abstract is on p.&nbsp;S106, but the annals are not among the journal’s numbered volumes. The meta-analysis table also labels this row with its reference 48, which is the Spanish validation; the intended reference is 49, cited correctly in its discussion <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
<p>The abstract states what the meta-analysis table omits: the task is counting numbers 1 to 20 plus the vowel /a/, with the voiced parts of both tasks equalized, in 150 speakers (113 dysphonic, 37 non-dysphonic); at 2.94 the sensitivity is 75.3% and the specificity 93.4%; diagnostic accuracy is 85.2% <span class="citation" data-cites="englert2019abstract">(<a href="#ref-englert2019abstract" role="doc-biblioref">Englert et al. 2019</a>)</span>. Inter-rater reliability for breathiness was below the recommended level (Fleiss κ = 0.353), and the abstract reports overall-grade and breathiness reliability separately, so the figures the meta-analysis tabulates for this row are the breathiness ones <span class="citation" data-cites="englert2019abstract">(<a href="#ref-englert2019abstract" role="doc-biblioref">Englert et al. 2019</a>)</span>. The later full Brazilian Portuguese validation <span class="citation" data-cites="englert2021avqi">(<a href="#ref-englert2021avqi" role="doc-biblioref">Englert et al. 2021</a>)</span> draws on the same sample and the same task but covers the AVQI only, so this abstract remains the only source for the Brazilian Portuguese ABI threshold at this task.</p>
<p>A second Brazilian Portuguese study, of 53 speakers, reports two ABI thresholds from the same people: 2.38 for counting 1–11 and 3.13 for the first sentence of a read text. Mean ABI scores were higher for reading <span class="citation" data-cites="englert2020material">(<a href="#ref-englert2020material" role="doc-biblioref">Englert et al. 2020</a>)</span>. The task alone moves the threshold by 0.75. The study had only 13 vocally healthy speakers, and its authors describe a full validation as still in process <span class="citation" data-cites="englert2020material">(<a href="#ref-englert2020material" role="doc-biblioref">Englert et al. 2020</a>)</span>. The 3.13 that appears for Brazilian Portuguese in the Finnish paper’s summary table <span class="citation" data-cites="kankare2023abi">(<a href="#ref-kankare2023abi" role="doc-biblioref">Kankare and Laukkanen 2023</a>)</span> is this reading-text value. That table has errors, and the Englert et al.&nbsp;table prints LR+ values that cannot be correct, so neither is used here for likelihood ratios. For Brazilian Portuguese, use the row that matches the task. The three published thresholds differ by task and sample rather than disagreeing: 2.38 for counting 1–11 (17 syllables) and 3.13 for the first sentence of a read text (32 syllables), both in the same 53 speakers <span class="citation" data-cites="englert2020material">(<a href="#ref-englert2020material" role="doc-biblioref">Englert et al. 2020</a>)</span>, and 2.94 for counting 1–20 (37 syllables) in 150 speakers <span class="citation" data-cites="englert2019abstract">(<a href="#ref-englert2019abstract" role="doc-biblioref">Englert et al. 2019</a>)</span>. The 2.94 row rests on the largest sample and on the task used by the Brazilian Portuguese AVQI validation <span class="citation" data-cites="englert2021avqi">(<a href="#ref-englert2021avqi" role="doc-biblioref">Englert et al. 2021</a>)</span>; the 2.38 and 3.13 rows state their Praat version, which it does not.</p>
<p>The Japanese row is no longer second-hand. The primary validation reports the same threshold of 3.44 that the meta-analysis tabulated, and adds the task, the Praat version and an AUC of 0.939 <span class="citation" data-cites="hosokawa2019abi">(<a href="#ref-hosokawa2019abi" role="doc-biblioref">Hosokawa et al. 2019</a>)</span>. The same first author published three Japanese papers: this ABI validation, an AVQI version 02.02 validation <span class="citation" data-cites="hosokawa2017avqi">(<a href="#ref-hosokawa2017avqi" role="doc-biblioref">Hosokawa et al. 2017</a>)</span>, and an AVQI version 03.01 validation not yet in this reference’s library.</p>
<p>The South Indian validation ran its ROC analysis twice, against breathiness and against overall grade, and reports two thresholds: 3.66 with breathiness as the reference standard (AUC 0.816, sensitivity 61.73%, specificity 94.94%) and 3.41 with overall grade (AUC 0.719, sensitivity 59.42%, specificity 79.19%) <span class="citation" data-cites="jayakumar2024abi">(<a href="#ref-jayakumar2024abi" role="doc-biblioref">Jayakumar and Benoy 2024</a>)</span>. The ABI targets breathiness, and the authors conclude it correlates better with breathiness than with grade, so the table above uses 3.66. The 3.41 is noted here only so that it is not mistaken for the South Indian ABI cutoff. Sensitivity at 3.66 is low: the threshold maximises the Youden index for that retrospective sample of 160 recordings, but it misses nearly four breathy voices in ten <span class="citation" data-cites="jayakumar2024abi">(<a href="#ref-jayakumar2024abi" role="doc-biblioref">Jayakumar and Benoy 2024</a>)</span>.</p>
<p>Across all published language validations the ABI thresholds now run from 2.35 in US English to 3.69 in Korean, with 2.68 Finnish, 2.94 Brazilian Portuguese (counting 1–20), 2.97 Persian, and 3.66 Malayalam and Kannada in between <span class="citation" data-cites="castillo2023avqi kankare2023abi aghajanzadeh2025persian jayakumar2024abi">(<a href="#ref-castillo2023avqi" role="doc-biblioref">Castillo-Allendes et al. 2023</a>; <a href="#ref-kankare2023abi" role="doc-biblioref">Kankare and Laukkanen 2023</a>; <a href="#ref-aghajanzadeh2025persian" role="doc-biblioref">Aghajanzadeh et al. 2025</a>; <a href="#ref-jayakumar2024abi" role="doc-biblioref">Jayakumar and Benoy 2024</a>)</span>.</p>
</section>
<section id="confounds-and-cautions" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="confounds-and-cautions"><span class="header-section-number">10.5</span> Confounds and cautions</h2>
<p><strong>Language dependence of the threshold.</strong> Continuous speech is part of the index, so inter-language phonetic differences may influence the outcome, and cross-validation studies are needed to establish the ABI’s validity for each language. The meta-analysis nevertheless found ABI relatively robust to phonetic inter-language differences such as stress timing, syllable timing, and intonation <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
<p><strong>The Praat version matters.</strong> With the same ABI script and the same 218 German recordings, seven Praat versions formed three clusters. A CPPS bug introduced in Praat 6.0.44 and fixed in 6.0.47 cut sensitivity at the German threshold of 3.42 from 72% to 9% with version 6.0.46. Across the unaffected versions, mean differences were negligible, but single recordings differed by up to about 3 points <span class="citation" data-cites="stappenbeck2020praat">(<a href="#ref-stappenbeck2020praat" role="doc-biblioref">Stappenbeck et al. 2020</a>)</span>. Use the Praat version of the validation study for the language in question, or check a new version against an earlier one on test recordings <span class="citation" data-cites="stappenbeck2020praat">(<a href="#ref-stappenbeck2020praat" role="doc-biblioref">Stappenbeck et al. 2020</a>)</span>.</p>
<p><strong>Software requirement.</strong> The validation evidence applies to signal processing in Praat with the customised ABI script; the meta-analysis excluded studies not using them <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
<p><strong>Equal task proportion.</strong> ABI results based on unequal proportions of continuous speech and sustained vowel were treated as a risk of bias <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
<p><strong>Hardware and recording conditions.</strong> Each validation study has unique acoustic settings and hardware, limiting comparability between studies <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. The Spanish validation recorded in a soundproof booth with a head-mounted condenser microphone at 44.1 kHz / 16 bit <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.</p>
<p><strong>Evidence base.</strong> The meta-analysis rests on six studies. Pooled sensitivity showed high heterogeneity (I² = 89.7%, <em>P</em> &lt; .001), while specificity heterogeneity was low (I² = 45.5). The Brazilian Portuguese study reached only low inter-rater reliability for breathiness (Fleiss κ = 0.353, below the 0.41 regarded as the minimum) <span class="citation" data-cites="englert2019abstract barsties2021abi">(<a href="#ref-englert2019abstract" role="doc-biblioref">Englert et al. 2019</a>; <a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>, with a sample skewed toward normal and mild breathiness (43% normal, 41% mild, 11% moderate, 5% severe) <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
<p><strong>Not a stand-alone screen.</strong> Not all voice disorders are detected by ABI — that cannot be expected from a measure of one perceptual dimension; higher diagnostic accuracy requires combining measures of different dimensions <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>. Further investigations of external and internal validity remain necessary <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.</p>
</section>
<section id="validation" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="validation"><span class="header-section-number">10.6</span> Validation</h2>
<p>The development study established the Dutch threshold of 3.44 with AUC 0.948 <span class="citation" data-cites="barsties2017abi delgado2018avqi">(<a href="#ref-barsties2017abi" role="doc-biblioref">Barsties v. Latoszek et al. 2017</a>; <a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. The Spanish validation reported a threshold of 3.40 with AUC 0.921 <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. The 2021 meta-analysis pooled six validation studies spanning more than 3600 voice samples and confirmed the ABI as a robust, valid objective measure of breathiness, with pooled sensitivity 0.84 and specificity 0.92 <span class="citation" data-cites="barsties2021abi">(<a href="#ref-barsties2021abi" role="doc-biblioref">Barsties v. Latoszek et al. 2021</a>)</span>.</p>
</section>
<section id="compute-it-in-phonalab" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="compute-it-in-phonalab"><span class="header-section-number">10.7</span> Compute it in PhonaLab</h2>
<blockquote class="blockquote">
<p><strong><a href="https://phonalab.com">Open PhonaLab →</a></strong></p>
<p><em>PhonaLab is developed by the author of this reference; see <a href="./intro.html#competing-interests">Competing interests</a>.</em></p>
<p>Upload a sustained vowel and a continuous speech sample to compute ABI on your own recording, alongside the AVQI computed from the same material.</p>
</blockquote>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aghajanzadeh2025persian" class="csl-entry" role="listitem">
Aghajanzadeh, Mahshid, Saeed Saeedi, Shohreh Jalaie, Kiarash Esarian, and Ben Barsties v. Latoszek. 2025. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> and the <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in the <span>Persian</span> Language.”</span> <em>Journal of Voice</em> 39 (6): 1700.e9–15. <a href="https://doi.org/10.1016/j.jvoice.2023.07.002">https://doi.org/10.1016/j.jvoice.2023.07.002</a>.
</div>
<div id="ref-barsties2021abi" class="csl-entry" role="listitem">
Barsties v. Latoszek, Ben, Geun-Hyo Kim, Jonathan Delgado Hernández, et al. 2021. <span>“The Validity of the <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in the Evaluation of Breathy Voice Quality: A Meta-Analysis.”</span> <em>Clinical Otolaryngology</em> 46 (1): 31–40. <a href="https://doi.org/10.1111/coa.13629">https://doi.org/10.1111/coa.13629</a>.
</div>
<div id="ref-barsties2020german" class="csl-entry" role="listitem">
Barsties v. Latoszek, Ben, Bernhard Lehnert, and Ben Janotte. 2020. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> Version 03.01 and <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in <span>German</span>.”</span> <em>Journal of Voice</em> 34 (1): 157.e17–25. <a href="https://doi.org/10.1016/j.jvoice.2018.07.026">https://doi.org/10.1016/j.jvoice.2018.07.026</a>.
</div>
<div id="ref-barsties2017abi" class="csl-entry" role="listitem">
Barsties v. Latoszek, Ben, Youri Maryn, Ellen Gerrits, and Marc De Bodt. 2017. <span>“The <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> (<span>ABI</span>): A Multivariate Acoustic Model for Breathiness.”</span> <em>Journal of Voice</em> 31 (4): 511.e11–27. <a href="https://doi.org/10.1016/j.jvoice.2016.11.017">https://doi.org/10.1016/j.jvoice.2016.11.017</a>.
</div>
<div id="ref-barsties2018meta" class="csl-entry" role="listitem">
Barsties v. Latoszek, Ben, Youri Maryn, Ellen Gerrits, and Marc De Bodt. 2018. <span>“A Meta-Analysis: Acoustic Measurement of Roughness and Breathiness.”</span> <em>Journal of Speech, Language, and Hearing Research</em> 61 (2): 298–323. <a href="https://doi.org/10.1044/2017_JSLHR-S-16-0188">https://doi.org/10.1044/2017_JSLHR-S-16-0188</a>.
</div>
<div id="ref-castillo2023avqi" class="csl-entry" role="listitem">
Castillo-Allendes, Adrián, Juliana Codino, Lady Catherine Cantor-Cutiva, et al. 2023. <span>“Clinical Utility and Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> and <span>Acoustic</span> <span>Breathiness</span> Indexes for Voice Disorder Assessment in <span>English</span> Speakers.”</span> <em>Journal of Clinical Medicine</em> 12 (24): 7679. <a href="https://doi.org/10.3390/jcm12247679">https://doi.org/10.3390/jcm12247679</a>.
</div>
<div id="ref-delgado2018avqi" class="csl-entry" role="listitem">
Delgado Hernández, Jonathan, Nieves M. León Gómez, Alejandra Jiménez, Laura M. Izquierdo, and Ben Barsties v. Latoszek. 2018. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> Version 03.01 and the <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in the <span>Spanish</span> Language.”</span> <em>Annals of Otology, Rhinology &amp; Laryngology</em> 127 (5): 317–26. <a href="https://doi.org/10.1177/0003489418761096">https://doi.org/10.1177/0003489418761096</a>.
</div>
<div id="ref-englert2019abstract" class="csl-entry" role="listitem">
Englert, Marina Taborda, Youri Maryn, Mara Behlau, and Ben Barsties v. Latoszek. 2019. <span>“Validation of the <span>AVQI</span> 03.01 and the <span>ABI</span> to the <span>Brazilian</span> <span>Portuguese</span> Language.”</span> <em>Annals of the 18th Congress of the Otorhinolaryngology Foundation</em> (S<span>ã</span>o Paulo, Brazil), August, S106.
</div>
<div id="ref-englert2021avqi" class="csl-entry" role="listitem">
Englert, Marina, Ben Barsties v. Latoszek, Youri Maryn, and Mara Behlau. 2021. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span>, Version 03.01, to the <span>Brazilian</span> <span>Portuguese</span> Language.”</span> <em>Journal of Voice</em> 35 (1): 160.e15–21. <a href="https://doi.org/10.1016/j.jvoice.2019.07.024">https://doi.org/10.1016/j.jvoice.2019.07.024</a>.
</div>
<div id="ref-englert2020material" class="csl-entry" role="listitem">
Englert, Marina, Livia Lima, and Mara Behlau. 2020. <span>“<span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> and <span>Acoustic</span> <span>Breathiness</span> <span>Index</span>: Analysis with Different Speech Material in the <span>Brazilian</span> <span>Portuguese</span>.”</span> <em>Journal of Voice</em> 34 (5): 810.e11–17. <a href="https://doi.org/10.1016/j.jvoice.2019.03.015">https://doi.org/10.1016/j.jvoice.2019.03.015</a>.
</div>
<div id="ref-hosokawa2017avqi" class="csl-entry" role="listitem">
Hosokawa, Kiyohito, Ben Barsties, Toshihiko Iwahashi, et al. 2017. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> in the <span>Japanese</span> Language.”</span> <em>Journal of Voice</em> 31 (2): 260.e1–9. <a href="https://doi.org/10.1016/j.jvoice.2016.05.010">https://doi.org/10.1016/j.jvoice.2016.05.010</a>.
</div>
<div id="ref-hosokawa2019abi" class="csl-entry" role="listitem">
Hosokawa, Kiyohito, Ben Barsties von Latoszek, Carlos Ariel Ferrer-Riesgo, et al. 2019. <span>“Acoustic <span>Breathiness</span> <span>Index</span> for the <span>Japanese</span>-Speaking Population: Validation Study and Exploration of Affecting Factors.”</span> <em>Journal of Speech, Language, and Hearing Research</em> 62 (8): 2617–31. <a href="https://doi.org/10.1044/2019_JSLHR-S-19-0077">https://doi.org/10.1044/2019_JSLHR-S-19-0077</a>.
</div>
<div id="ref-jayakumar2024abi" class="csl-entry" role="listitem">
Jayakumar, T., and Jesnu Jose Benoy. 2024. <span>“Validation of <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> (<span>ABI</span>) in the <span>South</span> <span>Indian</span> Population.”</span> <em>Journal of Voice</em> 38 (6): 1528.e1–9. <a href="https://doi.org/10.1016/j.jvoice.2022.05.006">https://doi.org/10.1016/j.jvoice.2022.05.006</a>.
</div>
<div id="ref-kankare2023abi" class="csl-entry" role="listitem">
Kankare, Elina, and Anne-Maria Laukkanen. 2023. <span>“Validation of the <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in Speakers of <span>Finnish</span> Language.”</span> <em>Journal of Clinical Medicine</em> 12 (24): 7607. <a href="https://doi.org/10.3390/jcm12247607">https://doi.org/10.3390/jcm12247607</a>.
</div>
<div id="ref-stappenbeck2020praat" class="csl-entry" role="listitem">
Stappenbeck, Lydia, Ben Barsties v. Latoszek, Ben Janotte, and Bernhard Lehnert. 2020. <span>“<span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> and <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> as Two Examples for Strengths and Weaknesses of Free Software in Medicine.”</span> <em>Biomedical Signal Processing and Control</em> 59: 101938. <a href="https://doi.org/10.1016/j.bspc.2020.101938">https://doi.org/10.1016/j.bspc.2020.101938</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/voicemeasures\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./avqi.html" class="pagination-link" aria-label="Acoustic Voice Quality Index (AVQI)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Acoustic Voice Quality Index (AVQI)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./release-notes.html" class="pagination-link" aria-label="Release notes and errata">
        <span class="nav-page-text">Release notes and errata</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Jorge C. Lucero · Text: CC BY 4.0 · Code: MIT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/LuceroJC/voice-measures/edit/main/abi.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/LuceroJC/voice-measures/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>