<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Acoustic Voice Quality Index (AVQI) – Acoustic Measures of Voice Quality</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./abi.html" rel="next">
<link href="./cpps.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5c01c0ce2b51dbeda25ce515ef8205e7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Cloudflare Web Analytics --><script type="module" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;: &quot;b81dffd01ef647da838f61336a77571c&quot;}"></script><!-- End Cloudflare Web Analytics -->

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./avqi.html">Part IV — Composite Indices</a></li><li class="breadcrumb-item"><a href="./avqi.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Acoustic Voice Quality Index (AVQI)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Acoustic Measures of Voice Quality</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/LuceroJC/voice-measures" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I — Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-signal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Signal Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-signal-typing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Signal Typing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-pipeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Pipeline Dependence and Reference Values</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III — Noise and Harmonic Structure</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./cpps.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Cepstral Peak Prominence (CPP and CPPS)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV — Composite Indices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./avqi.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Acoustic Voice Quality Index (AVQI)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./abi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Acoustic Breathiness Index (ABI)</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#definition" id="toc-definition" class="nav-link active" data-scroll-target="#definition"><span class="header-section-number">6.1</span> Definition</a></li>
  <li><a href="#computation" id="toc-computation" class="nav-link" data-scroll-target="#computation"><span class="header-section-number">6.2</span> Computation</a>
  <ul class="collapse">
  <li><a href="#speech-material-and-concatenation" id="toc-speech-material-and-concatenation" class="nav-link" data-scroll-target="#speech-material-and-concatenation"><span class="header-section-number">6.2.1</span> Speech material and concatenation</a></li>
  <li><a href="#component-measures" id="toc-component-measures" class="nav-link" data-scroll-target="#component-measures"><span class="header-section-number">6.2.2</span> Component measures</a></li>
  <li><a href="#regression-equation-version-03.01" id="toc-regression-equation-version-03.01" class="nav-link" data-scroll-target="#regression-equation-version-03.01"><span class="header-section-number">6.2.3</span> Regression equation (version 03.01)</a></li>
  <li><a href="#versions-02.02-and-03.01" id="toc-versions-02.02-and-03.01" class="nav-link" data-scroll-target="#versions-02.02-and-03.01"><span class="header-section-number">6.2.4</span> Versions 02.02 and 03.01</a></li>
  </ul></li>
  <li><a href="#what-it-captures" id="toc-what-it-captures" class="nav-link" data-scroll-target="#what-it-captures"><span class="header-section-number">6.3</span> What it captures</a></li>
  <li><a href="#normative-data" id="toc-normative-data" class="nav-link" data-scroll-target="#normative-data"><span class="header-section-number">6.4</span> Normative data</a></li>
  <li><a href="#confounds-and-cautions" id="toc-confounds-and-cautions" class="nav-link" data-scroll-target="#confounds-and-cautions"><span class="header-section-number">6.5</span> Confounds and cautions</a></li>
  <li><a href="#validation" id="toc-validation" class="nav-link" data-scroll-target="#validation"><span class="header-section-number">6.6</span> Validation</a></li>
  <li><a href="#compute-it-in-phonalab" id="toc-compute-it-in-phonalab" class="nav-link" data-scroll-target="#compute-it-in-phonalab"><span class="header-section-number">6.7</span> Compute it in PhonaLab</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/LuceroJC/voice-measures/edit/main/avqi.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/LuceroJC/voice-measures/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./avqi.html">Part IV — Composite Indices</a></li><li class="breadcrumb-item"><a href="./avqi.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Acoustic Voice Quality Index (AVQI)</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Acoustic Voice Quality Index (AVQI)</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Living draft.</strong> This chapter reflects the sources cited below and will be revised as further sources are incorporated. Found an error? Use the <em>Report an issue</em> link in the sidebar.</p>
</div>
</div>
<section id="definition" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="definition"><span class="header-section-number">6.1</span> Definition</h2>
<p>The Acoustic Voice Quality Index (AVQI) is an objective method to quantify the severity of overall voice quality in concatenated continuous speech and sustained phonation segments <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. It is a multivariate construct based on linear regression that combines six acoustic markers into a single score for the whole voice sample <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. That score represents the overall voice quality — the hoarseness level — of the sample <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.</p>
<p>The index was proposed by <span class="citation" data-cites="maryn2010ecological">Maryn, Corthals, et al. (<a href="#ref-maryn2010ecological" role="doc-biblioref">2010</a>)</span> and was one of the first measures to combine both speech types <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. The rationale for the combination: sustained vowels are easily elicited and less affected by articulation and dialect, while continuous speech is more representative of a patient’s daily voice <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.</p>
</section>
<section id="computation" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="computation"><span class="header-section-number">6.2</span> Computation</h2>
<section id="speech-material-and-concatenation" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="speech-material-and-concatenation"><span class="header-section-number">6.2.1</span> Speech material and concatenation</h3>
<p>The subject sustains the vowel [a:] for longer than 3 seconds, and a 3-second mid-vowel portion is selected. The subject also reads a phonetically balanced text aloud at comfortable pitch and loudness. For AVQI version 03.01 in Dutch, the continuous-speech part is trimmed to the first 34 syllables of the text, the 3-second [a:] segment is appended, and the result is saved as a single sound file <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. Acoustic analysis is applied only to the voiced segments of the continuous speech — extracted by an automated Praat detection script — plus the appended vowel segment <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.</p>
</section>
<section id="component-measures" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="component-measures"><span class="header-section-number">6.2.2</span> Component measures</h3>
<p>All six parameters are obtained in Praat from the concatenated signal <span class="citation" data-cites="barsties2016avqi delgado2018avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>; <a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>:</p>
<div id="tbl-avqi-components" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-avqi-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: The six AVQI components <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.
</figcaption>
<div aria-describedby="tbl-avqi-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Definition</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Smoothed cepstral peak prominence (CPPS)</td>
<td>Distance between the first rahmonic’s peak and the point of equal quefrency on the regression line through the smoothed cepstrum — see the <a href="./cpps.html">CPPS chapter</a></td>
</tr>
<tr class="even">
<td>Harmonics-to-noise ratio (HNR)</td>
<td>Base-10 logarithm of the ratio between periodic energy and noise energy, × 10</td>
</tr>
<tr class="odd">
<td>Shimmer local (Shim)</td>
<td>Absolute mean difference between amplitudes of successive periods, divided by the average amplitude</td>
</tr>
<tr class="even">
<td>Shimmer local dB (ShdB)</td>
<td>Base-10 logarithm of the difference between amplitudes of successive periods, × 20</td>
</tr>
<tr class="odd">
<td>General slope of the spectrum (Slope)</td>
<td>Difference between the energy in 0–1000 Hz and in 1000–10000 Hz of the long-term average spectrum</td>
</tr>
<tr class="even">
<td>Tilt of the spectral trendline (Tilt)</td>
<td>The same difference computed on the trendline through the long-term average spectrum</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="regression-equation-version-03.01" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="regression-equation-version-03.01"><span class="header-section-number">6.2.3</span> Regression equation (version 03.01)</h3>
<p>As printed by <span class="citation" data-cites="barsties2016avqi">Barsties and Maryn (<a href="#ref-barsties2016avqi" role="doc-biblioref">2016</a>)</span>:</p>
<p><span class="math display">\[
\text{AVQI}_{03.01} = \bigl(4.152 - 0.177\,\text{CPPS} - 0.006\,\text{HNR}
- 0.037\,\text{Shim} + 0.941\,\text{ShdB}
+ 0.01\,\text{Slope} + 0.093\,\text{Tilt}\bigr) \times 2.8902
\]</span></p>
<p>The published Praat script displays the resulting score on a 0–10 axis, marked green below the Dutch threshold of 2.43 and red above it <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>One equation, two misprints
</div>
</div>
<div class="callout-body-container callout-body">
<p>Two validation papers print this equation differently. <span class="citation" data-cites="barsties2020german">Barsties v. Latoszek et al. (<a href="#ref-barsties2020german" role="doc-biblioref">2020</a>)</span> print the HNR term as “(0.0006-HNR)” and <span class="citation" data-cites="delgado2018avqi">Delgado Hernández et al. (<a href="#ref-delgado2018avqi" role="doc-biblioref">2018</a>)</span> as “(0.0006 − HNR)”, both with a minus sign where a multiplication is expected; <span class="citation" data-cites="delgado2018avqi">Delgado Hernández et al. (<a href="#ref-delgado2018avqi" role="doc-biblioref">2018</a>)</span> also print the Tilt coefficient as 0.0993. The other sources — <span class="citation" data-cites="barsties2016avqi">Barsties and Maryn (<a href="#ref-barsties2016avqi" role="doc-biblioref">2016</a>)</span> (text and appendix script), <span class="citation" data-cites="englert2021avqi">Englert et al. (<a href="#ref-englert2021avqi" role="doc-biblioref">2021</a>)</span>, and <span class="citation" data-cites="castillo2023avqi">Castillo-Allendes et al. (<a href="#ref-castillo2023avqi" role="doc-biblioref">2023</a>)</span> — give 0.006 × HNR and 0.093 × Tilt, as above. All printed forms were checked against the publisher PDFs, so the differences are in the publications. When implementing the index, take the coefficients from the Praat script printed in the appendix of <span class="citation" data-cites="barsties2016avqi">Barsties and Maryn (<a href="#ref-barsties2016avqi" role="doc-biblioref">2016</a>)</span> rather than from an equation retyped in a later paper.</p>
</div>
</div>
</section>
<section id="versions-02.02-and-03.01" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="versions-02.02-and-03.01"><span class="header-section-number">6.2.4</span> Versions 02.02 and 03.01</h3>
<p>In the earlier AVQI versions the analyzed continuous-speech part was much shorter than the constant 3-second vowel part (1.53 s of voiced speech in Dutch, 1.99 s in Japanese) <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. Version 03.01 balances the analyzed durations of the two speech types by expanding the continuous-speech sample from 17–22 syllables to around 34 syllables, for higher ecological validity and balanced internal consistency <span class="citation" data-cites="barsties2016avqi delgado2018avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>; <a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. Early AVQI workflows required both SpeechTool and Praat; once CPPS was implemented in Praat, the index ran in Praat alone, with highly comparable outcomes <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.</p>
<p>The regression-based combination of measures over a concatenated sample was explored for tracheoesophageal (alaryngeal) voice by <span class="citation" data-cites="maryn2009cepstral">Maryn et al. (<a href="#ref-maryn2009cepstral" role="doc-biblioref">2009</a>)</span>, where a two-factor model combining CPP with the prominence of the second spectral harmonic reached <em>r<sub>s</sub></em> = 0.87 with listener judgments.</p>
</section>
</section>
<section id="what-it-captures" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="what-it-captures"><span class="header-section-number">6.3</span> What it captures</h2>
<p>The AVQI quantifies overall voice quality as judged by the grade (G) of the GRBAS scale — the degree of hoarseness or voice abnormality <span class="citation" data-cites="barsties2016avqi delgado2018avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>; <a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. Concurrent validity with mean perceptual G is strong: <em>r</em> = 0.815 in the Dutch external validation (66.4% of variance) <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span> and <em>r</em> = 0.835 in Spanish (69.7% of variance) <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. CPPS is the main factor in the multivariate model <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. <span class="citation" data-cites="barsties2018meta">Barsties v. Latoszek et al. (<a href="#ref-barsties2018meta" role="doc-biblioref">2018</a>)</span> report, from the earlier overall-voice-quality meta-analysis of Maryn, Roy et al.&nbsp;(2009), weighted correlations for CPPS of 0.63 for sustained vowels and 0.88 for continuous speech.</p>
<p>A previous AVQI investigation <span class="citation" data-cites="maryn2010avqi">(<a href="#ref-maryn2010avqi" role="doc-biblioref">Maryn, De Bodt, et al. 2010</a>)</span> reported high sensitivity to voice changes through voice therapy <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.</p>
</section>
<section id="normative-data" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="normative-data"><span class="header-section-number">6.4</span> Normative data</h2>
<p>Diagnostic thresholds separate normophonic from hoarse voices, with hoarseness defined as mean perceptual grade G ≥ 0.5 <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. The threshold differs between AVQI versions and languages <span class="citation" data-cites="barsties2020german">(<a href="#ref-barsties2020german" role="doc-biblioref">Barsties v. Latoszek et al. 2020</a>)</span>, so each row states its language and pipeline. Use the row validated for the patient’s language and the AVQI version in use; see <a href="./foundations-pipeline.html">Pipeline Dependence and Reference Values</a>.</p>
<div id="tbl-avqi-thresholds" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-avqi-thresholds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: AVQI 03.01 diagnostic thresholds. Dutch: <span class="citation" data-cites="barsties2016avqi">Barsties and Maryn (<a href="#ref-barsties2016avqi" role="doc-biblioref">2016</a>)</span>; Spanish: <span class="citation" data-cites="delgado2018avqi">Delgado Hernández et al. (<a href="#ref-delgado2018avqi" role="doc-biblioref">2018</a>)</span>; German: <span class="citation" data-cites="barsties2020german">Barsties v. Latoszek et al. (<a href="#ref-barsties2020german" role="doc-biblioref">2020</a>)</span>; French: <span class="citation" data-cites="pommee2020avqi">Pommée et al. (<a href="#ref-pommee2020avqi" role="doc-biblioref">2020</a>)</span>; Brazilian Portuguese: <span class="citation" data-cites="englert2021avqi">Englert et al. (<a href="#ref-englert2021avqi" role="doc-biblioref">2021</a>)</span> (150 speakers) and <span class="citation" data-cites="englert2020material">Englert et al. (<a href="#ref-englert2020material" role="doc-biblioref">2020</a>)</span> (53 speakers, two tasks); US English: <span class="citation" data-cites="castillo2023avqi">Castillo-Allendes et al. (<a href="#ref-castillo2023avqi" role="doc-biblioref">2023</a>)</span>; Persian: <span class="citation" data-cites="aghajanzadeh2025persian">Aghajanzadeh et al. (<a href="#ref-aghajanzadeh2025persian" role="doc-biblioref">2025</a>)</span>; pooled: <span class="citation" data-cites="jayakumar2024avqi">Jayakumar and Benoy (<a href="#ref-jayakumar2024avqi" role="doc-biblioref">2024</a>)</span>. Praat versions for the Dutch, Spanish and German rows are those cited in each paper’s reference list.
</figcaption>
<div aria-describedby="tbl-avqi-thresholds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Language</th>
<th>Sample</th>
<th>Pipeline</th>
<th>Threshold</th>
<th>Sensitivity</th>
<th>Specificity</th>
<th>AUC</th>
<th>Class</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dutch, external validation</td>
<td>970 dysphonic, 88 normal</td>
<td>AVQI 03.01; Praat 5.3.57</td>
<td>2.43</td>
<td>0.785</td>
<td>0.932</td>
<td>0.923</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Spanish</td>
<td>136 dysphonic, 47 normal</td>
<td>AVQI 03.01; Praat 6.0.22</td>
<td>2.28</td>
<td>0.748</td>
<td>0.946</td>
<td>0.905</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>German</td>
<td>175 dysphonic, 43 healthy; 27 syllables</td>
<td>AVQI 03.01; Praat 5.3.57</td>
<td>1.85</td>
<td>0.72</td>
<td>0.90</td>
<td>0.90</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>French</td>
<td>90 ENT patients, 30 controls; 27 syllables</td>
<td>AVQI 03.01; Praat version not stated; recorded at 11,025 Hz</td>
<td>2.33</td>
<td>0.598</td>
<td>1.00</td>
<td>0.788</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>Brazilian Portuguese</td>
<td>113 dysphonic, 37 nondysphonic; counting 1–11 (17 syllables)</td>
<td>AVQI 03.01 script; Praat 6.0.40</td>
<td>1.33</td>
<td>0.788</td>
<td>0.906</td>
<td>0.904</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Brazilian Portuguese, counting 1–11</td>
<td>40 dysphonic, 13 healthy; 17 syllables</td>
<td>AVQI 03.01; Praat 6.0.06</td>
<td>1.16</td>
<td>0.86</td>
<td>0.80</td>
<td>0.87</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>Brazilian Portuguese, reading text</td>
<td>same 53 speakers; 32 syllables</td>
<td>AVQI 03.01; Praat 6.0.06</td>
<td>1.56</td>
<td>0.886</td>
<td>1.00</td>
<td>0.963</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>US English</td>
<td>148 with voice disorders, 49 non-clinic-seeking; first 22 syllables of the Rainbow Passage</td>
<td>AVQI 03.01 in VOXplot 2.0.0; Praat 6.3.06 for extraction</td>
<td>1.17</td>
<td>0.62</td>
<td>0.95</td>
<td>0.84</td>
<td>language-conditional</td>
</tr>
<tr class="odd">
<td>Persian</td>
<td>136 dysphonic, 45 vocally healthy; 20 syllables, durations balanced</td>
<td>AVQI 03.01 in VOXplot, version not stated</td>
<td>1.63</td>
<td>0.732</td>
<td>0.91</td>
<td>0.850</td>
<td>language-conditional</td>
</tr>
<tr class="even">
<td>Pooled: eight AVQI v03 studies (context only)</td>
<td>12 languages</td>
<td>multiple</td>
<td>none; study thresholds ranged 1.33–3.15</td>
<td>0.82</td>
<td>0.92</td>
<td>0.94 (SROC)</td>
<td>meta-analytic</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The pooled row is descriptive context, not a cutoff. Its sensitivity was highly heterogeneous across studies (<em>I</em>² = 95.3%), its specificity much less so (<em>I</em>² = 16.4%) <span class="citation" data-cites="jayakumar2024avqi">(<a href="#ref-jayakumar2024avqi" role="doc-biblioref">Jayakumar and Benoy 2024</a>)</span>.</p>
<p>Two further thresholds appear in the literature only second-hand and are not used as cutoffs here, because their pipeline is not stated where they are reported: 2.43 with sensitivity 0.936 and specificity 1.00 for an internal Dutch validation, as reported by <span class="citation" data-cites="barsties2016avqi">Barsties and Maryn (<a href="#ref-barsties2016avqi" role="doc-biblioref">2016</a>)</span>, and 2.06 with sensitivity 0.721 and specificity 0.938 for Japanese, as reported by <span class="citation" data-cites="delgado2018avqi">Delgado Hernández et al. (<a href="#ref-delgado2018avqi" role="doc-biblioref">2018</a>)</span>.</p>
<p>The Japanese figure needs care. It belongs to an AVQI version 03.01 validation for Japanese that this reference has not yet obtained. A separate paper by the same group validated AVQI version <strong>02.02</strong> in Japanese and reports a threshold of 3.15, with sensitivity 72.5% and specificity 95.2%, on a standardized syllable number of 22 <span class="citation" data-cites="hosokawa2017avqi">(<a href="#ref-hosokawa2017avqi" role="doc-biblioref">Hosokawa et al. 2017</a>)</span>. The two are not rival estimates: they belong to different versions of the index, with different regression weights and different speech-material lengths, so 3.15 cannot be compared with any threshold in <a href="#tbl-avqi-thresholds" class="quarto-xref">Table&nbsp;<span>6.2</span></a>. Always pair an AVQI threshold with its version.</p>
<p>Likelihood ratios at the optimal threshold: LR+ = 11.54, LR− = 0.23 (Dutch external validation) <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>; LR+ = 13.85, LR− = 0.26 (Spanish, threshold chosen by the Youden index) <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>; LR+ = 7.40, LR− = 0.31 (German) <span class="citation" data-cites="barsties2020german">(<a href="#ref-barsties2020german" role="doc-biblioref">Barsties v. Latoszek et al. 2020</a>)</span>; LR+ = 8.38, LR− = 0.23 (Brazilian Portuguese) <span class="citation" data-cites="englert2021avqi">(<a href="#ref-englert2021avqi" role="doc-biblioref">Englert et al. 2021</a>)</span>; LR+ = 12.46, LR− = 0.40 (US English) <span class="citation" data-cites="castillo2023avqi">(<a href="#ref-castillo2023avqi" role="doc-biblioref">Castillo-Allendes et al. 2023</a>)</span>. The LR+ values printed by <span class="citation" data-cites="englert2020material">Englert et al. (<a href="#ref-englert2020material" role="doc-biblioref">2020</a>)</span> are below 1 or negative and cannot be correct, so they are not reproduced here.</p>
<p>The original AVQI, which carried no version number, reported two cutoff options: 2.36 (sensitivity 91%, specificity 59%) and 2.95 (sensitivity 74%, specificity 96%). The authors suggest 2.95 may be more appropriate when the main interest is screening <span class="citation" data-cites="maryn2010ecological">(<a href="#ref-maryn2010ecological" role="doc-biblioref">Maryn, Corthals, et al. 2010</a>)</span>. These values apply to that version only.</p>
<p>The US English validation standardized the continuous-speech part at 22 syllables of the Rainbow Passage, recorded in a quiet environment (ambient noise below 35 dB) with a head-mounted microphone at 44.1 kHz / 16 bit, and computed the index in VOXplot 2.0.0, which the authors state uses established Praat algorithms and the same equation <span class="citation" data-cites="castillo2023avqi">(<a href="#ref-castillo2023avqi" role="doc-biblioref">Castillo-Allendes et al. 2023</a>)</span>. Its threshold, 1.17, lies below the range of the AVQI meta-analysis, whose literature search ended in July 2021 <span class="citation" data-cites="jayakumar2024avqi">(<a href="#ref-jayakumar2024avqi" role="doc-biblioref">Jayakumar and Benoy 2024</a>)</span>. The authors note that other English dialects and accents remain to be examined <span class="citation" data-cites="castillo2023avqi">(<a href="#ref-castillo2023avqi" role="doc-biblioref">Castillo-Allendes et al. 2023</a>)</span>.</p>
</section>
<section id="confounds-and-cautions" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="confounds-and-cautions"><span class="header-section-number">6.5</span> Confounds and cautions</h2>
<p><strong>Language-specific standardization is required.</strong> The continuous-speech part must be trimmed to a syllable count that yields about 3 seconds of voiced speech, and the count differs by language: 34 syllables in Dutch, 33 in Spanish, 30 in Japanese for AVQIv3 <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>.</p>
<p><strong>Thresholds differ by language, and by version.</strong> Reported optimal AVQI version 03.01 cutoffs are 2.43 (Dutch), 2.28 (Spanish) and 2.06 (Japanese). The differences are small, which may indicate that AVQI is relatively insulated from inter-language phonetic differences <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. The validations since widen the spread: 1.85 German, 2.33 French, 1.33 Brazilian Portuguese, 1.63 Persian. A version 02.02 threshold sits on a different scale altogether, as the Japanese version 02.02 value of 3.15 shows <span class="citation" data-cites="hosokawa2017avqi">(<a href="#ref-hosokawa2017avqi" role="doc-biblioref">Hosokawa et al. 2017</a>)</span>.</p>
<p><strong>Equal proportion of the two speech tasks.</strong> Earlier work found the sustained vowel dominating the final AVQI score more than the continuous speech. <span class="citation" data-cites="barsties2015consistency">Barsties and Maryn (<a href="#ref-barsties2015consistency" role="doc-biblioref">2015</a>)</span> tested three speech-material durations against that: 17 syllables plus 3 s of sustained phonation, a customised continuous-speech length plus 3 s, and a whole text plus 3 s. Concurrent validity was comparable across all three (<em>r</em><sub>s</sub> 0.891 to 0.929), but precision was best, and the two tasks’ contributions balanced, in the middle condition. This is the reasoning behind the standardized syllable count that the later validations use.</p>
<p><strong>Recording conditions matter.</strong> Validation recordings were made in sound- treated rooms with head-mounted condenser microphones at 44.1 kHz / 16 bit, with environmental noise verified against a signal-to-noise norm <span class="citation" data-cites="barsties2016avqi delgado2018avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>; <a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>. The AVQI script itself states that reliable analysis requires optimal data-acquisition conditions <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.</p>
<p><strong>The Praat version matters.</strong> With the same AVQI 03.01 script and the same 218 German recordings, seven Praat versions formed three clusters. Praat 6.0.44 introduced a bug in the CPPS computation that 6.0.47 fixed. With version 6.0.46, AVQI scores were on average about 4.2 points lower, and sensitivity at the German threshold of 1.85 fell from 72% to 23%. Across the unaffected versions, mean differences were negligible, but single recordings differed by up to about 0.6 points <span class="citation" data-cites="stappenbeck2020praat">(<a href="#ref-stappenbeck2020praat" role="doc-biblioref">Stappenbeck et al. 2020</a>)</span>. The authors recommend using the Praat version of the validation study for the language in question, or checking a new version against an earlier one on test recordings <span class="citation" data-cites="stappenbeck2020praat">(<a href="#ref-stappenbeck2020praat" role="doc-biblioref">Stappenbeck et al. 2020</a>)</span>.</p>
<p><strong>Sampling rate.</strong> The French validation recorded at 11,025 Hz <span class="citation" data-cites="pommee2020avqi">(<a href="#ref-pommee2020avqi" role="doc-biblioref">Pommée et al. 2020</a>)</span>, so its signals contain nothing above about 5.5 kHz. The AVQI script computes the LTAS slope and trend-line tilt over bands that reach 10 kHz <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>, so two of the six components are computed on a narrower band than in the other validations. Treat the French threshold as applying to recordings made at that rate.</p>
<p><strong>Report the version.</strong> Versions 02.02 and 03.01 differ in the length of the continuous-speech part (17 vs.&nbsp;34 syllables) and in the regression weighting <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. Report the version with every score.</p>
<p><strong>Base rates affect ROC statistics.</strong> The Dutch external validation sample contained 8% normophonia and 92% dysphonia; likelihood ratios were used because they are less vulnerable to base-rate differences than ROC statistics alone <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.</p>
<p><strong>Voicing detection is part of the pipeline.</strong> Voiced segments of continuous speech are extracted automatically by a Praat script before measurement <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>.</p>
</section>
<section id="validation" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="validation"><span class="header-section-number">6.6</span> Validation</h2>
<p>Across 1118 subjects in two studies, AVQI 03.01 showed a homogeneous weighted mean correlation of <em>r</em> = 0.821 with perceptual overall voice quality, against <em>r</em> = 0.790 for the initial AVQI model pooled over 507 subjects <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. In the same pooled analysis, the Dysphonia Severity Index reached a heterogeneous weighted mean <em>r</em> = 0.524 and the Cepstral Spectral Index of Dysphonia <em>r</em> = 0.788 (sustained vowel) and 0.748 (continuous speech); AVQI 03.01 reached the highest concurrent validity among these multiparametric indices <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span>. Language validations include Dutch <span class="citation" data-cites="barsties2016avqi">(<a href="#ref-barsties2016avqi" role="doc-biblioref">Barsties and Maryn 2016</a>)</span> and Spanish <span class="citation" data-cites="delgado2018avqi">(<a href="#ref-delgado2018avqi" role="doc-biblioref">Delgado Hernández et al. 2018</a>)</span>, with Japanese figures reported in the latter.</p>
</section>
<section id="compute-it-in-phonalab" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="compute-it-in-phonalab"><span class="header-section-number">6.7</span> Compute it in PhonaLab</h2>
<blockquote class="blockquote">
<p><strong><a href="https://phonalab.com">Open PhonaLab →</a></strong></p>
<p><em>PhonaLab is developed by the author of this reference; see <a href="./intro.html#competing-interests">Competing interests</a>.</em></p>
<p>Upload a sustained vowel and a continuous speech sample to compute AVQI on your own recording, with the version and language protocol reported alongside the score.</p>
</blockquote>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aghajanzadeh2025persian" class="csl-entry" role="listitem">
Aghajanzadeh, Mahshid, Saeed Saeedi, Shohreh Jalaie, Kiarash Esarian, and Ben Barsties v. Latoszek. 2025. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> and the <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in the <span>Persian</span> Language.”</span> <em>Journal of Voice</em> 39 (6): 1700.e9–15. <a href="https://doi.org/10.1016/j.jvoice.2023.07.002">https://doi.org/10.1016/j.jvoice.2023.07.002</a>.
</div>
<div id="ref-barsties2015consistency" class="csl-entry" role="listitem">
Barsties, Ben, and Youri Maryn. 2015. <span>“The Improvement of Internal Consistency of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span>.”</span> <em>American Journal of Otolaryngology</em> 36: 647–56. <a href="https://doi.org/10.1016/j.amjoto.2015.04.012">https://doi.org/10.1016/j.amjoto.2015.04.012</a>.
</div>
<div id="ref-barsties2016avqi" class="csl-entry" role="listitem">
Barsties, Ben, and Youri Maryn. 2016. <span>“External Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> Version 03.01 with Extended Representativity.”</span> <em>Annals of Otology, Rhinology &amp; Laryngology</em> 125 (7): 571–83. <a href="https://doi.org/10.1177/0003489416636131">https://doi.org/10.1177/0003489416636131</a>.
</div>
<div id="ref-barsties2020german" class="csl-entry" role="listitem">
Barsties v. Latoszek, Ben, Bernhard Lehnert, and Ben Janotte. 2020. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> Version 03.01 and <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in <span>German</span>.”</span> <em>Journal of Voice</em> 34 (1): 157.e17–25. <a href="https://doi.org/10.1016/j.jvoice.2018.07.026">https://doi.org/10.1016/j.jvoice.2018.07.026</a>.
</div>
<div id="ref-barsties2018meta" class="csl-entry" role="listitem">
Barsties v. Latoszek, Ben, Youri Maryn, Ellen Gerrits, and Marc De Bodt. 2018. <span>“A Meta-Analysis: Acoustic Measurement of Roughness and Breathiness.”</span> <em>Journal of Speech, Language, and Hearing Research</em> 61 (2): 298–323. <a href="https://doi.org/10.1044/2017_JSLHR-S-16-0188">https://doi.org/10.1044/2017_JSLHR-S-16-0188</a>.
</div>
<div id="ref-castillo2023avqi" class="csl-entry" role="listitem">
Castillo-Allendes, Adrián, Juliana Codino, Lady Catherine Cantor-Cutiva, et al. 2023. <span>“Clinical Utility and Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> and <span>Acoustic</span> <span>Breathiness</span> Indexes for Voice Disorder Assessment in <span>English</span> Speakers.”</span> <em>Journal of Clinical Medicine</em> 12 (24): 7679. <a href="https://doi.org/10.3390/jcm12247679">https://doi.org/10.3390/jcm12247679</a>.
</div>
<div id="ref-delgado2018avqi" class="csl-entry" role="listitem">
Delgado Hernández, Jonathan, Nieves M. León Gómez, Alejandra Jiménez, Laura M. Izquierdo, and Ben Barsties v. Latoszek. 2018. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> Version 03.01 and the <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> in the <span>Spanish</span> Language.”</span> <em>Annals of Otology, Rhinology &amp; Laryngology</em> 127 (5): 317–26. <a href="https://doi.org/10.1177/0003489418761096">https://doi.org/10.1177/0003489418761096</a>.
</div>
<div id="ref-englert2021avqi" class="csl-entry" role="listitem">
Englert, Marina, Ben Barsties v. Latoszek, Youri Maryn, and Mara Behlau. 2021. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span>, Version 03.01, to the <span>Brazilian</span> <span>Portuguese</span> Language.”</span> <em>Journal of Voice</em> 35 (1): 160.e15–21. <a href="https://doi.org/10.1016/j.jvoice.2019.07.024">https://doi.org/10.1016/j.jvoice.2019.07.024</a>.
</div>
<div id="ref-englert2020material" class="csl-entry" role="listitem">
Englert, Marina, Livia Lima, and Mara Behlau. 2020. <span>“<span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> and <span>Acoustic</span> <span>Breathiness</span> <span>Index</span>: Analysis with Different Speech Material in the <span>Brazilian</span> <span>Portuguese</span>.”</span> <em>Journal of Voice</em> 34 (5): 810.e11–17. <a href="https://doi.org/10.1016/j.jvoice.2019.03.015">https://doi.org/10.1016/j.jvoice.2019.03.015</a>.
</div>
<div id="ref-hosokawa2017avqi" class="csl-entry" role="listitem">
Hosokawa, Kiyohito, Ben Barsties, Toshihiko Iwahashi, et al. 2017. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> in the <span>Japanese</span> Language.”</span> <em>Journal of Voice</em> 31 (2): 260.e1–9. <a href="https://doi.org/10.1016/j.jvoice.2016.05.010">https://doi.org/10.1016/j.jvoice.2016.05.010</a>.
</div>
<div id="ref-jayakumar2024avqi" class="csl-entry" role="listitem">
Jayakumar, Thirunavukkarasu, and Jesnu Jose Benoy. 2024. <span>“<span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> (<span>AVQI</span>) in the Measurement of Voice Quality: A Systematic Review and Meta-Analysis.”</span> <em>Journal of Voice</em> 38 (5): 1055–69. <a href="https://doi.org/10.1016/j.jvoice.2022.03.018">https://doi.org/10.1016/j.jvoice.2022.03.018</a>.
</div>
<div id="ref-maryn2010ecological" class="csl-entry" role="listitem">
Maryn, Youri, Paul Corthals, Paul Van Cauwenberge, Nelson Roy, and Marc De Bodt. 2010. <span>“Toward Improved Ecological Validity in the Acoustic Measurement of Overall Voice Quality: Combining Continuous Speech and Sustained Vowels.”</span> <em>Journal of Voice</em> 24 (5): 540–55. <a href="https://doi.org/10.1016/j.jvoice.2008.12.014">https://doi.org/10.1016/j.jvoice.2008.12.014</a>.
</div>
<div id="ref-maryn2010avqi" class="csl-entry" role="listitem">
Maryn, Youri, Marc De Bodt, and Nelson Roy. 2010. <span>“The <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span>: Toward Improved Treatment Outcomes Assessment in Voice Disorders.”</span> <em>Journal of Communication Disorders</em> 43 (3): 161–74. <a href="https://doi.org/10.1016/j.jcomdis.2009.12.004">https://doi.org/10.1016/j.jcomdis.2009.12.004</a>.
</div>
<div id="ref-maryn2009cepstral" class="csl-entry" role="listitem">
Maryn, Youri, Catherine Dick, Caroline Vandenbruaene, Tom Vauterin, and Tinne Jacobs. 2009. <span>“Spectral, Cepstral, and Multivariate Exploration of Tracheoesophageal Voice Quality in Continuous Speech and Sustained Vowels.”</span> <em>The Laryngoscope</em> 119 (12): 2384–94. <a href="https://doi.org/10.1002/lary.20620">https://doi.org/10.1002/lary.20620</a>.
</div>
<div id="ref-pommee2020avqi" class="csl-entry" role="listitem">
Pommée, Timothy, Youri Maryn, Camille Finck, and Dominique Morsomme. 2020. <span>“Validation of the <span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span>, Version 03.01, in <span>French</span>.”</span> <em>Journal of Voice</em> 34 (4): 646.e11–26. <a href="https://doi.org/10.1016/j.jvoice.2018.12.008">https://doi.org/10.1016/j.jvoice.2018.12.008</a>.
</div>
<div id="ref-stappenbeck2020praat" class="csl-entry" role="listitem">
Stappenbeck, Lydia, Ben Barsties v. Latoszek, Ben Janotte, and Bernhard Lehnert. 2020. <span>“<span>Acoustic</span> <span>Voice</span> <span>Quality</span> <span>Index</span> and <span>Acoustic</span> <span>Breathiness</span> <span>Index</span> as Two Examples for Strengths and Weaknesses of Free Software in Medicine.”</span> <em>Biomedical Signal Processing and Control</em> 59: 101938. <a href="https://doi.org/10.1016/j.bspc.2020.101938">https://doi.org/10.1016/j.bspc.2020.101938</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/voicemeasures\.org");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./cpps.html" class="pagination-link" aria-label="Cepstral Peak Prominence (CPP and CPPS)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Cepstral Peak Prominence (CPP and CPPS)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./abi.html" class="pagination-link" aria-label="Acoustic Breathiness Index (ABI)">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Acoustic Breathiness Index (ABI)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Jorge C. Lucero · Text: CC BY 4.0 · Code: MIT</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/LuceroJC/voice-measures/edit/main/avqi.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/LuceroJC/voice-measures/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>