{
  "hash": "164321f375dbc09f77d8935c8e45f5e5",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Harmonic-to-Noise Ratio (HNR)\"\nexecute:\n  echo: true\njupyter: python3\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code for this figure\"\n---\n\n::: {.callout-note}\n**Living draft.** This chapter reflects the sources cited below and will be\nrevised as further sources are incorporated. Found an error? Use the *Report an\nissue* link in the sidebar.\n:::\n\n\n## Definition\n\n**The question the harmonic-to-noise ratio asks is how much of the sound is\nperiodic at all.** Unlike jitter and shimmer it does not compare one cycle with\nthe next: it weighs the energy that repeats against the energy that does not.\n\nA characteristic feature of hoarseness is the replacement of harmonics by noise\nenergy: aperiodic sound intensifies at the expense of the periodic signal. It\nis therefore reasonable to conclude that the best index of hoarseness might be\nthe ratio of one to the other, and that is what the harmonic-to-noise ratio\nmeasures [@baken2000clinical].\n\nThe conceptual basis is simple. The voice is considered to have two components,\nperfectly periodic waves and random noise. The H/N ratio is the mean amplitude\nof the wave divided by the mean amplitude of the isolated noise components for\nthe train of waves, and for convenience it is expressed in decibels\n[@baken2000clinical].\n\n\n@fig-hnr shows the harmonics being replaced by noise as the ratio falls.\n\n::: {#cell-fig-hnr .cell execution_count=2}\n``` {.python .cell-code}\nfs, f0 = 16000, 150.0\nT0 = 1.0 / f0\nncyc = 90\nrng = np.random.default_rng(5)\nper = T0 * (1 + 0.002 * rng.standard_normal(ncyc))\namp = 1 + 0.02 * rng.standard_normal(ncyc)\n\nlevels = [(\"Little noise\", -35), (\"Moderate noise\", -12), (\"Noise-dominated\", 6)]\n\ndef log_spectrum(x, fs, win_s=0.040, nfft=4096):\n    L = int(win_s * fs)\n    seg = x[len(x) // 2 - L // 2: len(x) // 2 + L // 2] * np.hanning(L)\n    S = np.abs(np.fft.rfft(seg, nfft))\n    f = np.fft.rfftfreq(nfft, 1 / fs)\n    return f, 20 * np.log10(S + 1e-12)\n\nfig, axes = plt.subplots(2, 3, figsize=(7.4, 4.5),\n                         gridspec_kw={\"height_ratios\": [0.85, 1.2]})\nshow_s = 0.030\nfor j, (name, nd) in enumerate(levels):\n    x = vs.synth_vowel(per, amp, fs, noise_rel_db=nd, seed=21)\n    t = np.arange(len(x)) / fs\n\n    ax = axes[0, j]\n    m = t <= show_s\n    ax.plot(t[m] * 1e3, x[m], color=vs.INK, lw=0.85)\n    ax.set_title(name, color=vs.INK)\n    ax.set_ylim(-1.2, 1.2); ax.set_yticks([]); ax.set_xlim(0, show_s * 1e3)\n    ax.set_xlabel(\"Time (ms)\", labelpad=1)\n    if j == 0: ax.set_ylabel(\"Pressure\")\n    vs.style_axes(ax); ax.grid(False)\n\n    ax = axes[1, j]\n    f, S = log_spectrum(x, fs)\n    k = f <= 4000\n    S = S - S[k].max()\n    if j == 0:\n        for h in np.arange(f0, 4000, f0):\n            ax.axvline(h / 1e3, color=vs.GRID, lw=0.7, zorder=0)\n    ax.plot(f[k] / 1e3, S[k], color=vs.BLUE, lw=0.8)\n    ax.set_ylim(-70, 6); ax.set_xlim(0, 4)\n    ax.set_xlabel(\"Frequency (kHz)\")\n    if j == 0: ax.set_ylabel(\"Level (dB, relative)\")\n    vs.style_axes(ax)\n    ax.text(0.97, 0.96, f\"noise at {nd:+d} dB\\nrelative to voicing\",\n            transform=ax.transAxes, ha=\"right\", va=\"top\", fontsize=8,\n            color=vs.INK, linespacing=1.35)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The same synthetic vowel (F0 = 150 Hz) with three levels of added aspiration noise. Top: the waveform. Bottom: the log spectrum to 4 kHz; the faint vertical lines in the left-hand panel mark the harmonic series. With little noise the harmonics stand clear to 4 kHz. As noise rises they fill in from the top down, so that in the right-hand panel the comb survives only below about 1.5 kHz. This is the replacement of harmonics by noise energy that the ratio is built to quantify. The labels give the noise level used in the synthesis relative to the voiced component; they are not measured HNR values, and the signals are synthetic and illustrative.](hnr_files/figure-html/fig-hnr-output-1.png){#fig-hnr width=804 height=484 fig-alt='Three columns. The top waveforms grow progressively more irregular from left to right. The spectra below show a clear comb of harmonic peaks on the left, partly filled in at the middle, and smeared above about 1.5 kHz on the right.'}\n:::\n:::\n\n\n## Computation\n\nThe ratio approach was taken by Kojima and colleagues and by Kitajima, but\ntheir computational procedure was complex and inconvenient. The textbook does\nnot call theirs the first, and the Behlau chapter names earlier work — Isshiki,\nYanagihara and Morimoto (1966), Hiroto (1967), and Emanuel and Sansone (1969)\n[@behlauespecialista]. It was soon\nimproved upon by Yumoto and colleagues, whose procedure was to objectify and\nquantify the features that appear in the spectrogram of the hoarse voice\n[@baken2000clinical].\n\n**Normalized noise energy** (NNE) is a related measure with a different\nstrategy. Regular changes over the sampling interval influence the assessment\nof noise, analogous to the long-term drift problems that plague jitter and\nshimmer. NNE avoids that contaminating influence by basing its analysis on\nrelatively few vocal periods and detecting the noise component of the spectrum\nwith a specially designed **adaptive comb filter**. Like the H/N ratio it is\nexpressed in decibels [@baken2000clinical].\n\nAn older family of measures quantifies **spectral noise** directly rather than\nas a ratio. In one such method, speakers sustained vowels for 7 s at a\nmonitored 75 dB SPL; a 2-second segment was looped and repeatedly scanned by a\nspectrum analyzer at a very narrow 3 Hz bandwidth, and the minimum noise value\nwas measured for each 100-Hz segment of the spectrum from 200 to 8000 Hz\n[@baken2000clinical].\n\n## Normative data\n\n**This reference publishes no HNR cutoff.**\n\nHNR is strongly implementation-dependent, and no source reviewed here states a\nPraat version and settings for an HNR reference value. Under the rule in\n[Pipeline Dependence and Reference Values](foundations-pipeline.qmd), the\nabsence is declared rather than filled.\n\n| Population | Task | Pipeline | Cutoff | Class |\n|---|---|---|---|---|\n| Any, measured in Praat | Sustained /a/ | — | No published reference | — |\n\n: HNR reference values for a Praat-based pipeline. {#tbl-hnr-cutoffs}\n\nThe values below come from other pipelines and are shown for context only.\n\n| Population | Task | Value | Pipeline | Class |\n|---|---|---|---|---|\n| 22 men and 20 women with no demonstrable vocal disorder | Sustained /a/ | Mean H/N 11.9 dB (SD 2.32), range 7.0–17.0; sexes did not differ significantly; 95 per cent confidence limit 7.4 dB | Yumoto's method; software and settings not stated | unclassified (software and settings not stated) |\n| 12 men and 8 women with various laryngeal pathologies, before surgery | Sustained /a/ | Mean H/N 1.6 dB; after surgery 11.3 dB (SD 3.13), range 5.9–17.6, with about 95 per cent reaching the expected normal range | As above | unclassified (software and settings not stated) |\n| 14 women per group, three age groups | Sustained vowel, onset and offset discarded | Young 7.82 dB, middle-aged 7.86 dB, elderly 5.54 dB; the elderly group differed significantly from both younger groups | Kay Elemetrics CSL 4300; Yumoto's method except that the signal is not preemphasized; 51.2 kHz, 2-second frame; MiniDisc at 44.1 kHz | unclassified for a Praat pipeline |\n| Brazilian women and men, modal register | Sustained vowel | Women 9.4 dB; men 8.6 dB | Soundscope 2.0; algorithm and settings not stated; reported second-hand | unclassified (algorithm and settings not stated) |\n| Women and men, modal register | Sustained vowel | Women 13.9 dB; men 11.8 dB | Soundscope 2.0; second-hand | unclassified (algorithm and settings not stated) |\n| Women and men, falsetto register | Sustained vowel | Women 15.6 dB; men 15 dB | Soundscope 2.0; second-hand | unclassified (algorithm and settings not stated) |\n| Pulse (basal) register | Sustained vowel | Not reliably computable: the noise component is high | Soundscope 2.0; second-hand | unclassified (algorithm and settings not stated) |\n| NNE, normal limit | Not stated | Normal up to −10 dB; values nearer zero, such as −5 or −3 dB, strongly indicate phonatory aperiodicity | Not stated | unclassified (pipeline not stated) |\n\n: HNR and NNE values from other pipelines, for context only. Yumoto and spectral-noise rows: @baken2000clinical. Age-group row: @ferrand2002hnr. Brazilian and NNE rows: @behlauespecialista. {#tbl-hnr-context}\n\n### Where the 7 dB bound comes from\n\nThe widely repeated figure traces to Yumoto's series, whose 95 per cent\nconfidence limit for normal speakers was **7.4 dB**, with a normal mean of\n11.9 dB [@baken2000clinical]. The same 7.4 dB figure is reported independently\n[@ferrand2002hnr]. It is commonly carried rounded to 7 dB, with the stronger\nclaim that a ratio below 7 dB is necessarily pathological\n[@behlauespecialista].\n\nThree cautions follow. The bound belongs to the Yumoto algorithm family and is\nnot a cross-system constant. In Yumoto's own data, three of the twenty\npreoperative dysphonic subjects had ratios above the 7.4 dB limit, and they\nwere the ones with very slight clinical hoarseness [@baken2000clinical]. And\nin the age-group series above, the healthy young and middle-aged means of\n7.82 dB and 7.86 dB sit only just above the bound, while the elderly group's\nmean of 5.54 dB falls below it although the group was normally speaking\n[@ferrand2002hnr]. **A 7 dB floor applied to older speakers would classify\nhealthy voices as pathological.**\n\n## What it captures\n\nHNR rises with better harmonic structure and falls with more noise. It is lower\nin men and higher in women, and highest in falsetto, then modal, then pulse\nregister — so a value is interpretable only in the register in which the voice\nwas recorded [@behlauespecialista].\n\nReinke's oedema can give paradoxically high values: the source's statement is\nspecific to that condition, where the harmonic component present can keep the\nratio high. It does not generalise this to diffuse mass lesions, and it does\nnot state that HNR alone would therefore under-flag such voices. Small glottal\ngaps can give a low ratio or raised NNE,\nwithout exact correlation to the perceptual grade of dysphonia. The measure is\nuseful for monitoring the course of paralytic dysphonias and partial\nlaryngectomies [@behlauespecialista].\n\n**NNE discriminates dysphonic voices better than HNR.** In three groups of\nwomen — complete glottal coaptation, mid-posterior triangular gap, and vocal\nnodules — NNE was the *most sensitive* acoustic parameter and HNR did not\ndifferentiate the groups; F0 and jitter were also similar across groups, while\nshimmer was significantly higher in the nodule group [@behlauespecialista].\nPublished NNE data remain scarce. Preliminary reports suggest the measure\nperforms well in discriminating abnormal voices, but the same page records a\nnull result: in ten adult patients tested before and after treatment, NNE did\nnot differ significantly despite a significant reduction in jitter and\nshimmer and the patients' own report of improvement, and a significant change\nappeared only when NNE was restricted to energy between 1 and 4 kHz. The\ntextbook concludes that the clinical usefulness of NNE, or of some\nmodification of it, remains unclear [@baken2000clinical].\n\n**What NNE tracks perceptually.** McAllister, Sundberg and Hibi, as cited by\nthe textbook, reported a \"reasonable correlation\" between NNE and perceived\nbreathiness, hoarseness and roughness in 26 girls and 24 boys aged ten, normal\nand dysphonic. It was strongest for breathiness, .78 in girls and .77 in boys;\nless for hoarseness, .50 and .57; and least for roughness, .38 and .48\n[@baken2000clinical].\n\nThe two measures are complementary: HNR appears more informative in normal\nvoices, NNE in dysphonic ones [@behlauespecialista].\n\n## Confounds and cautions\n\n**The most recording-sensitive of the common measures.** In a three-system\ncomparison, only fundamental frequency was resistant to differences in\nrecording condition, and the harmonic-to-noise ratio was the *most sensitive*\nparameter of those examined [@behlauespecialista].\n\n**System dependence.** Different analysis systems may produce dissimilar\nresults when analysing the same signal, and until inter-laboratory standards\nare agreed upon, comparison of data sets must be undertaken with caution; the\nwarning is general to perturbation and noise analysis [@baken2000clinical].\nEvery HNR value in the table above therefore carries its pipeline and its\ncompatibility class, and a value whose analysis software is unstated cannot be\ncompared with one whose software is. See\n[Pipeline Dependence and Reference Values](foundations-pipeline.qmd).\n\n::: {.callout-note collapse=\"true\"}\n## Erratum, v0.3.0\n\nBefore v0.3.0 this section attributed to the Behlau chapter a statement that\nextraction methods are typically unreported in the older literature and that\nsoftware and version must be reported. The cited page covers only signal\ntyping, and no ingested source makes that claim. See the\n[release notes](release-notes.qmd).\n:::\n\n**Spectral noise alone is a weak discriminator.** Measured directly rather than\nas a ratio, spectral noise has been found to be only a fair differentiator of\nrough and abnormal voices, a result the textbook attributes to Emanuel and\nAustin [@baken2000clinical].\n\n**Harmonic amplitude does not fall indefinitely as noise rises.** Emanuel and\nWhitehead, as cited by the textbook, found that as interharmonic spectral noise\nincreases, energy at the harmonic frequencies does decrease, but only up to a\npoint [@baken2000clinical].\n\n**Vowel and fundamental frequency both matter.** Vowels differ in median noise\nlevel in a consistent order, and among normal children a high fundamental\nfrequency was associated with lower noise levels — though that relationship did\nnot hold for the dysphonic children in the same study [@baken2000clinical].\n\n**Signal typing applies.** As with jitter and shimmer, HNR is reliably\nmeasurable only on Type 1 signals [@titze1995workshop].\n\n## Points of disagreement\n\n**How firm is the 7 dB floor.** The Behlau chapter states that a ratio below\n7 dB is necessarily pathological [@behlauespecialista]. Yumoto's own series,\nthe origin of the figure, found three preoperative dysphonic subjects above the\n7.4 dB limit [@baken2000clinical], and the normally speaking elderly group\nabove averaged 5.54 dB, below it [@ferrand2002hnr]. The bound is a 95 per cent\nconfidence limit on one algorithm and one sample, not a diagnostic constant.\n\n**Cohort and software both move the normal range.** The two sets of Brazilian\nmodal-register means in @tbl-hnr-context differ by roughly 3 to 4 dB despite\nboth using the same program on Brazilian speakers [@behlauespecialista]. The\nsources reviewed here do not explain the gap. Any normative threshold used\nclinically should be tied to its extraction system and reference cohort rather\nthan treated as universal.\n\n**Whether HNR or NNE should be the primary clinical noise measure** remains\nopen, and the two sources reviewed do not agree. The Behlau chapter suggests\nHNR for normal voices and NNE for dysphonic ones [@behlauespecialista]. The\nEnglish textbook declines to endorse NNE, concluding that its clinical\nusefulness, or that of some modification of it, remains unclear\n[@baken2000clinical].\n\n## Compute it in PhonaLab\n\n> **[Open PhonaLab →](https://phonalab.com)**\n>\n> *PhonaLab is developed by the author of this reference; see\n> [Competing interests](intro.qmd#competing-interests).*\n>\n> PhonaLab reports HNR with its algorithm, settings and task stated alongside\n> the value. It deliberately shows **no normal band and no severity band** for\n> HNR, because no published reference value is compatible with its pipeline —\n> see @tbl-hnr-cutoffs. In particular it does not apply a 7 dB floor.\n\n",
    "supporting": [
      "hnr_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}