{
  "hash": "3bd296a9c0c46c4e4beaf0048ec83ae5",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Pipeline Dependence and Reference Values\"\nexecute:\n  echo: true\njupyter: python3\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code for this figure\"\n---\n\n::: {.callout-note}\n**Living draft.** This chapter explains why every reference value in this\nreference is reported with the pipeline that produced it. Measure chapters\npoint here from their Normative data sections. Found an error? Use the\n*Report an issue* link in the sidebar.\n:::\n\n\n## A value belongs to its pipeline\n\nAn acoustic voice measure is produced by a pipeline: the recording chain, the\nanalysis program and its version, the algorithm and its settings, the speech\nmaterial, and, for composite indices, the language and the perceptual\nreference used to set a cutoff. The number that comes out depends on the\npipeline as well as on the voice. A cutoff or a normative value is therefore\nvalid only for measurements made with the same or a compatible pipeline.\n\nThis is easy to miss. Programs label their output with the same names, such as\n\"mean jitter\" or \"percent shimmer\", and the shared labels suggest that results\nfrom different programs are comparable [@bielamowicz1996perturbation]. This\nchapter shows, from published comparisons, how far that suggestion fails, and\nsets out how the reference reports reference values as a result.\n\n## What counts as the pipeline\n\n| Pipeline element | Evidence that it changes the value |\n|---|---|\n| Analysis program | Three systems agreed on mean F0 (within 3 Hz) but not on jitter or shimmer, even with standardized recording and analysis procedures [@karnell1995perturbation]. |\n| Implementation of a named measure | Two programs that both compute relative average perturbation (RAP) gave significantly different percent jitter [@bielamowicz1996perturbation]. |\n| Algorithm details | For CPP, ADSV and Praat differ in voicing detection, window, interpolation, regression fit and regression range [@watts2017cpp]. |\n| Program settings | The same program gave a Rainbow Passage CPPS cutoff of 19.10 dB with factory settings [@sauder2017cpps] and 9.33 dB with published non-default settings [@murton2020cpp]. |\n| Program version | Three CPPS studies used three Praat versions (6.0.17, 6.0.40, 6.0.50), and the version should be reported [@buckley2023cpp]. One Praat release changed AVQI and ABI scores enough to invalidate their cutoffs [@stappenbeck2020praat]. |\n| Speech material | Stimulus had a large effect on cepstral values, larger than software; sex had a small effect [@buckley2023cpp]. |\n| Portion of a passage | Studies analysed the second sentence, the first 12 s, or sentences 2–3 of the Rainbow Passage [@sauder2017cpps; @murton2020cpp; @buckley2023cpp]. |\n| Index version and language | The AVQI threshold differs between versions and languages [@barsties2020german]. |\n| Perceptual reference | The AVQI development study counted a voice as normal only if all judges rated G = 0 [@maryn2010ecological]; later validations used mean G below 0.5 [@englert2021avqi; @pommee2020avqi]. |\n| Pre-processing | Digital differencing combined with a hardware pre-emphasis filter pre-emphasizes the signal twice [@kent2002acoustic, p. 64]. |\n| Automatic segment rejection | A program must not automatically and surreptitiously discard segments it deems unacceptable [@baken2000clinical, p. 132]. |\n\n: Pipeline elements shown to change measured values. {#tbl-pipeline-elements}\n\n## Evidence 1: perturbation measures across programs\n\nThe earliest systematic comparisons concerned jitter and shimmer. Karnell and\ncolleagues analysed the same 60 vowel tokens from 20 patients with three\nsystems. Mean F0 differed by less than 3 Hz, with correlations of .98 to 1.00.\nJitter correlations between systems were .29, .62 and .64, and shimmer\ncorrelations ranged from .26 to .42 [@karnell1995perturbation]. The authors\nadvise clinicians who use perturbation measures as objective measures to\nexamine their validity and reliability carefully [@karnell1995perturbation].\n\nBielamowicz and colleagues compared four systems on 50 dysphonic voices.\nOn the near-periodic (type 1) signals that all systems could analyse,\nrank-order correlations ranged from .33 to .80 for jitter and from .81 to .89\nfor percent shimmer, and mean HNR/SNR on the same voices ranged from 8.58 to\n21.31 dB across systems [@bielamowicz1996perturbation]. They note that a high\nrank-order correlation may mask significant differences in the values\nthemselves, and that programs which hide where cycle boundaries were placed\nmake it virtually impossible to check whether a perturbation analysis is valid\n[@bielamowicz1996perturbation].\n\n## Evidence 2: cepstral peak prominence across programs\n\nCepstral peak prominence is often recommended because it does not need F0\ntracking (see [Signal Typing](foundations-signal-typing.qmd)). It is not\npipeline-free. The two programs most used clinically, ADSV and Praat, compute\nit differently. ADSV discards frames with CPP below 0 dB as a simple voicing\ndetector, fits the regression line by least squares from 0.0001 s quefrency,\nand uses a Hamming window without interpolation. Praat applies no voicing\ndetection, fits a robust (Theil) line from 0.001 s, and uses a Gaussian window\nwith parabolic interpolation [@watts2017cpp].\n\nThe consequences are large:\n\n- On the same MEEI recordings of sustained /a/, the cutoff separating\n  voice-disordered from typical speakers was 11.46 dB for ADSV CPP and\n  14.45 dB for Praat CPPS [@murton2020cpp].\n- On the same 170 Rainbow Passage samples, ADSV CPPS ranged from 0.40 to\n  8.31 dB and Praat CPPS from 14.71 to 22.99 dB: the two ranges do not\n  overlap. The programs correlated at *r* = 0.88, and the authors conclude\n  that absolute values from the two programs cannot be compared directly\n  [@sauder2017cpps].\n- Watts and colleagues found Praat and ADSV CPP correlated at *r* = 0.92 to\n  0.96 in English, yet clearly different in magnitude. They suggest the\n  difference may be due particularly to the regression-line calculation, and\n  recommend comparing CPP data only with data from the identical program and\n  algorithm [@watts2017cpp].\n\n## Evidence 3: one program, different settings and material\n\nChanging the settings of a single program also moves the reference. With\nPraat 6.0.17 at factory settings on the second sentence of the Rainbow\nPassage, the CPPS cutoff was 19.10 dB [@sauder2017cpps]. With the settings\npublished by Watts and colleagues, on the first 12 s of the passage, the Praat\nCPPS cutoff was 9.33 dB [@murton2020cpp]. Buckley and colleagues point out both\ndifferences: the settings, and the portion of the passage analysed\n[@buckley2023cpp].\n\nBuckley and colleagues then measured 150 speakers without voice disorders,\naged 18 to 91 years, with the same Praat settings as Murton and colleagues.\n56% of the women and 65.3% of the men fell below the 9.33-dB cutoff, and all\nfell below the 19.10-dB cutoff. They conclude that cutoffs from ROC analysis do\nnot adequately represent speakers without voice disorders, and propose\nnormative lower limits 2 SD below the group mean instead: 6.40 dB (men) and\n6.49 dB (women) for the Rainbow Passage in Praat [@buckley2023cpp].\n\n@fig-cpp-references places these values on one axis.\n\n::: {#cell-fig-cpp-references .cell execution_count=2}\n``` {.python .cell-code}\n# Values as published. Kind: \"cut\" = ROC cutoff, \"norm\" = normative lower limit.\nrainbow = [\n    (\"ADSV\", \"Murton 2020 (first 12 s)\", 6.11, \"cut\"),\n    (\"ADSV\", \"Sauder 2017 (sentence 2, factory)\", 5.53, \"cut\"),\n    (\"ADSV\", \"Buckley 2023, men (sentences 2–3)\", 5.40, \"norm\"),\n    (\"ADSV\", \"Buckley 2023, women (sentences 2–3)\", 5.04, \"norm\"),\n    (\"Praat\", \"Murton 2020 (first 12 s, Watts settings)\", 9.33, \"cut\"),\n    (\"Praat\", \"Sauder 2017 (sentence 2, factory)\", 19.10, \"cut\"),\n    (\"Praat\", \"Buckley 2023, men (Watts settings)\", 6.40, \"norm\"),\n    (\"Praat\", \"Buckley 2023, women (Watts settings)\", 6.49, \"norm\"),\n]\nvowel = [\n    (\"ADSV\", \"Murton 2020\", 11.46, \"cut\"),\n    (\"ADSV\", \"Buckley 2023, men\", 8.86, \"norm\"),\n    (\"ADSV\", \"Buckley 2023, women\", 8.09, \"norm\"),\n    (\"Praat\", \"Murton 2020 (Watts settings)\", 14.45, \"cut\"),\n    (\"Praat\", \"Buckley 2023, men (Watts settings)\", 11.72, \"norm\"),\n    (\"Praat\", \"Buckley 2023, women (Watts settings)\", 11.05, \"norm\"),\n]\ncolors = {\"ADSV\": vs.ORANGE, \"Praat\": vs.BLUE}\n\nfig, axes = plt.subplots(2, 1, figsize=(7.2, 5.8), sharex=True,\n                         gridspec_kw={\"height_ratios\": [len(rainbow), len(vowel)]})\nfor ax, data, title in zip(axes, [rainbow, vowel], [\"Rainbow Passage\", \"Sustained /a/\"]):\n    y = np.arange(len(data))[::-1]\n    for yi, (prog, label, val, kind) in zip(y, data):\n        c = colors[prog]\n        if kind == \"cut\":\n            ax.plot(val, yi, marker=\"D\", ms=7, color=c, zorder=3)\n        else:\n            ax.plot(val, yi, marker=\"o\", ms=7, mfc=\"white\", mec=c, mew=1.8, zorder=3)\n        ax.text(val + 0.35, yi, f\"{val:.2f}\", va=\"center\", fontsize=8, color=vs.INK)\n    ax.set_yticks(y)\n    ax.set_yticklabels([f\"{p}: {l}\" for p, l, _, _ in data], fontsize=8)\n    ax.set_ylim(-0.7, len(data) - 0.3)\n    ax.axvline(12, color=vs.MUTED, lw=1, ls=\":\", zorder=1)\n    ax.set_title(title, color=vs.INK)\n    vs.style_axes(ax)\n    ax.grid(axis=\"y\", visible=False)\naxes[-1].set_xlim(0, 22)\naxes[-1].set_xlabel(\"CPP / CPPS (dB)\")\nhandles = [\n    plt.Line2D([], [], marker=\"D\", ls=\"\", color=vs.INK, ms=6, label=\"ROC cutoff\"),\n    plt.Line2D([], [], marker=\"o\", ls=\"\", mfc=\"white\", mec=vs.INK, mew=1.5, ms=6,\n               label=\"Normative lower limit (2 SD below mean)\"),\n    plt.Line2D([], [], marker=\"s\", ls=\"\", color=vs.ORANGE, ms=6, label=\"ADSV\"),\n    plt.Line2D([], [], marker=\"s\", ls=\"\", color=vs.BLUE, ms=6, label=\"Praat\"),\n]\nfig.legend(handles=handles, loc=\"lower center\", ncol=4, frameon=False, fontsize=8,\n           bbox_to_anchor=(0.55, 0.0))\nfig.tight_layout(rect=(0, 0.05, 1, 1))\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Published CPP reference values for the Rainbow Passage (left) and sustained /a/ (right), by program. Filled diamonds are ROC cutoffs between voice-disordered and typical speakers; open circles are normative lower limits for typical speakers (2 SD below the mean). Each label names the study and, where it matters, the settings or the portion of the passage analysed. The dotted line at 12 dB is illustrative: on sustained /a/, a value of 12 dB is above the ADSV cutoff (11.46 dB) and below the Praat cutoff (14.45 dB), so the same number points in opposite directions. Sources: Murton et al. (2020); Sauder et al. (2017); Buckley et al. (2023).](foundations-pipeline_files/figure-html/fig-cpp-references-output-1.png){#fig-cpp-references width=781 height=637 fig-alt='Two dot plots of decibel values. In both, ADSV references cluster at lower values (about 5 to 11 dB) and Praat references at higher values (about 6 to 19 dB). In the Rainbow Passage panel the two Praat cutoffs are 9.33 and 19.10 dB, far apart. A dotted vertical line marks 12 dB.'}\n:::\n:::\n\n\n## Evidence 4: composite indices across languages\n\nComposite indices add language to the pipeline, because their\ncontinuous-speech part is language-specific. The AVQI threshold differs\nbetween versions and languages [@barsties2020german], and the syllable count\nof the continuous-speech part is set separately for each language\n[@jayakumar2024avqi]. @fig-avqi-languages shows the published AVQI 03.01\nthresholds. A meta-analysis of eight AVQI v03 studies found thresholds from\n1.33 to 3.15 and did not derive a weighted threshold [@jayakumar2024avqi]; the\nUS English validation, published after its July 2021 search, reports 1.17\n[@castillo2023avqi]. ABI thresholds in the ABI meta-analysis range from 2.94\n(Brazilian Portuguese) to 3.69 (Korean) [@barsties2021abi], and the US English\nvalidation reports 2.35 [@castillo2023avqi]. Within one language the task\nmatters too: in the same 53 Brazilian Portuguese speakers, the ABI threshold\nwas 2.38 for counting and 3.13 for reading text, and the AVQI threshold 1.16\nand 1.56 [@englert2020material].\n\n::: {#cell-fig-avqi-languages .cell execution_count=3}\n``` {.python .cell-code}\navqi = [  # language, threshold\n    (\"US English\", 1.17),\n    (\"Brazilian Portuguese\", 1.33),\n    (\"German\", 1.85),\n    (\"Japanese\", 2.06),\n    (\"Spanish\", 2.28),\n    (\"French\", 2.33),\n    (\"Dutch\", 2.43),\n]\nfig, ax = plt.subplots(figsize=(7, 2.9))\nax.axvspan(1.33, 3.15, color=vs.GRID, alpha=0.8, lw=0)\nax.text(3.13, len(avqi) - 0.45, \"meta-analytic range, 8 studies to 2021\", ha=\"right\",\n        va=\"center\", fontsize=8, color=vs.INK)\ny = np.arange(len(avqi))\nfor yi, (lang, thr) in zip(y, avqi):\n    ax.plot(thr, yi, \"o\", ms=7, color=vs.BLUE, zorder=3)\n    ax.text(thr + 0.04, yi, f\"{thr:.2f}\", va=\"center\", fontsize=8, color=vs.INK)\nax.set_yticks(y)\nax.set_yticklabels([l for l, _ in avqi])\nax.set_xlim(1.0, 3.3)\nax.set_ylim(-0.6, len(avqi) - 0.1)\nax.set_xlabel(\"AVQI 03.01 threshold\")\nvs.style_axes(ax)\nax.grid(axis=\"y\", visible=False)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Published AVQI 03.01 thresholds by language (points) and the range reported across eight AVQI v03 studies in a meta-analysis (shaded band, 1.33–3.15). The meta-analysis did not derive a single weighted threshold. The US English study was published after the meta-analysis search. Sources: Castillo-Allendes et al. (2023); Englert et al. (2021); Barsties v. Latoszek et al. (2020); Delgado Hernández et al. (2018); Pommée et al. (2020); Barsties & Maryn (2016); Jayakumar & Benoy (2024).](foundations-pipeline_files/figure-html/fig-avqi-languages-output-1.png){#fig-avqi-languages width=760 height=309 fig-alt='A horizontal dot plot of AVQI thresholds: US English 1.17, Brazilian Portuguese 1.33, German 1.85, Japanese 2.06, Spanish 2.28, French 2.33, Dutch 2.43, over a shaded band from 1.33 to 3.15.'}\n:::\n:::\n\n\nThe sources disagree on why the thresholds differ (see Points of\ndisagreement), but not on the practical consequence: a threshold validated in\none language is not a threshold for another.\n\n## Evidence 5: one script, different program versions\n\nEven a fixed script is not a fixed pipeline, because the program underneath\nit changes. @stappenbeck2020praat ran the AVQI 03.01 and ABI scripts on the\nsame 218 German recordings under seven Praat versions. Five were versions\ncited in validation studies; the other two were 6.0.46 and 6.0.48, the most\nrecent at the start of the study. The versions formed three clusters:\n5.3.55, 5.3.57 and 6.0.06; 6.0.21, 6.0.22 and 6.0.48; and 6.0.46 alone,\nwhich carries a bug in the CPPS computation introduced in 6.0.44 and removed\nin 6.0.47 [@stappenbeck2020praat].\n\n::: {#cell-fig-praat-versions .cell execution_count=4}\n``` {.python .cell-code}\nclusters = [\"5.3.55 / 5.3.57 / 6.0.06\", \"6.0.21 / 6.0.22 / 6.0.48\", \"6.0.46 (CPPS bug)\"]\nsens = {\"AVQI\": [72, 71, 23], \"ABI\": [72, 70, 9]}\nfig, ax = plt.subplots(figsize=(7, 2.4))\ny = np.arange(len(clusters))[::-1]\nfor (name, vals), col, dy in zip(sens.items(), (vs.BLUE, vs.ORANGE), (0.12, -0.12)):\n    ax.plot(vals, y + dy, \"o\", ms=7, color=col, label=name, zorder=3)\n    for v, yi in zip(vals, y + dy):\n        ax.text(v + 2, yi, f\"{v}%\", va=\"center\", fontsize=8, color=vs.INK)\nax.set_yticks(y)\nax.set_yticklabels(clusters)\nax.set_xlim(0, 100)\nax.set_ylim(-0.6, len(clusters) - 0.4)\nax.set_xlabel(\"Sensitivity at the German threshold (%)\")\nax.legend(frameon=False, fontsize=8, loc=\"lower right\")\nvs.style_axes(ax)\nax.grid(axis=\"y\", visible=False)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Sensitivity of AVQI and ABI at the German thresholds (AVQI 1.85, ABI 3.42) when the same scripts run on the same 218 recordings under three clusters of Praat versions. The cluster containing 6.0.46, with its CPPS bug, misses most dysphonic voices, while specificity rises to 100% and correlations with perceptual ratings stay at 0.84–0.86. Source: Stappenbeck et al. (2020).](foundations-pipeline_files/figure-html/fig-praat-versions-output-1.png){#fig-praat-versions width=760 height=254 fig-alt='Dot plot of sensitivity by Praat version cluster. AVQI: 72% for versions 5.3.55 to 6.0.06, 71% for 6.0.21 to 6.0.48, 23% for 6.0.46. ABI: 72%, 70%, and 9%.'}\n:::\n:::\n\n\nThe bug lowered AVQI scores by about 4.2 points on average, so most\ndysphonic voices fell below the threshold (@fig-praat-versions). The\ncorrelations with perceptual ratings and the AUC stayed high in all three\nclusters, so validity statistics alone would not have revealed the problem\n[@stappenbeck2020praat]. Between the two unaffected clusters, mean\ndifferences were not significant, but single recordings differed by up to\nabout 0.6 AVQI points and 3 ABI points. The authors suspect a further change\nbetween 6.0.06 and 6.0.21, and recommend either the Praat version of the\nvalidation study or a check of each new version against an earlier one on\ntest recordings [@stappenbeck2020praat].\n\n## How this reference reports reference values\n\nEvery Normative data table in the measure chapters carries two provenance\ncolumns.\n\n- **Pipeline**: the program, version and non-default settings as stated by the\n  source (\"not stated\" when the source does not say), the speech material, and\n  the language where the measure depends on it.\n- **Evidence**: one of three classes.\n\n| Class | Meaning | Use |\n|---|---|---|\n| primary | One study, one stated pipeline | Valid for measurements with the same or a compatible pipeline |\n| language-specific | Validation of an index in a named language | Valid for that language and the stated pipeline |\n| pooled | Meta-analysis across studies or analysis systems | Descriptive context only; never a cutoff |\n\n: Evidence classes used in Normative data tables. {#tbl-evidence-classes}\n\nWhere the reviewed sources give no usable reference for a population, task or\nlanguage, the table says so instead of borrowing a value from another\npipeline. The measured value can still be reported; what is withheld is the\ncomparison.\n\n## Using a reference value\n\n1. **Match the pipeline.** Compare CPP data only with data obtained using the\n   identical program and algorithm [@watts2017cpp]; compare ADSV values with\n   ADSV norms and Praat values with Praat norms [@buckley2023cpp].\n2. **Match the material and the language.** Check the task, the portion of\n   the passage, and, for composite indices, the language of the validation.\n3. **Report the pipeline with every value.** The 1994 workshop consensus asks\n   that the perturbation function and measure be made explicit in any\n   perturbation analysis, and that F0, intensity and voice quality be defined\n   when differences are reported [@titze1995workshop]. The Praat version should\n   be reported for CPPS [@buckley2023cpp].\n4. **Do not convert across programs without a published conversion for your\n   exact pipeline.** Watts and colleagues give regression equations from ADSV\n   CPP to Praat CPPS, separately for each language and task [@watts2017cpp];\n   they apply only to those settings and stimuli.\n\n## Caveats\n\n- **High correlation does not mean interchangeable values.** Even correlations\n  close to 1.0 can leave nontrivial residual error [@watts2017cpp].\n- **Opaque software.** Buckley and colleagues note that ADSV's voicing\n  detection is not detailed in its user manual [@buckley2023cpp].\n- **Recording conditions.** Hardware, microphone placement, environmental noise\n  and software are known to affect perturbation measures; their effect on CPP\n  and CPPS remains unclear [@barsties2018meta].\n- **Explanations are hypotheses.** Buckley and colleagues suggest their wider\n  age range may explain their lower values [@buckley2023cpp], although age\n  group had no significant effect in their own data.\n- **Inter-laboratory standards.** Until they are agreed, comparison of data\n  sets must be undertaken with caution [@baken2000clinical, p. 194].\n\n## Points of disagreement\n\n- **Why AVQI thresholds differ between languages.** @englert2021avqi suggest\n  that a low threshold may be a characteristic of Brazilian Portuguese, and\n  that Brazilian listeners may be less tolerant of vocal deviation.\n  @barsties2020german relate the low German threshold to the small syllable\n  count of its continuous-speech part. @jayakumar2024avqi suggest extreme\n  thresholds could be due to the standardized syllable number; their own\n  tables list the highest v03 threshold, 3.15, for a Korean study.\n- **Sauder's 19.10 dB.** @buckley2023cpp describe 19.10 dB as the average\n  CPPS in @sauder2017cpps. In the original it is the ROC cutoff; the mean for\n  speakers without voice disorders was 20.11 dB.\n\n",
    "supporting": [
      "foundations-pipeline_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}