{
  "hash": "741139f6d460b75e046698ec894016ea",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Signal Typing\"\nexecute:\n  echo: true\njupyter: python3\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code for this figure\"\n---\n\n::: {.callout-note}\n**Living draft.** This chapter presents the classification that gates every\nmeasure in Parts II to IV. Later chapters refer to the types by number in their\nCaveats sections. All example signals are synthetic; the code is shown under\neach figure and is MIT licensed. Found an error? Use the *Report an issue* link\nin the sidebar.\n:::\n\n\n## Why signal typing comes first\n\nF0 is the rate at which a cyclic waveform repeats. An aperiodic signal has no\nrepeating waveform and therefore has no F0 [@baken2000clinical, p. 152]. Jitter,\nshimmer and harmonics-to-noise ratio all start from an identified F0 or\nperiod, so they inherit this limit. The acoustic signals of many voice\ndisorders do not have a periodicity that allows automatic measurement of F0\nor of cycle amplitudes [@ludlow2018measuring, p. 378].\n\nAnalysis software does not protect the user from this. A computer-based system\nmay calculate a putative F0 for any signal, even an aperiodic one, and the\nnumber it displays need not have any meaning [@baken2000clinical, p. 152].\nChecking the signal is the user's responsibility. It is often skipped: Ludlow,\nKent and Gray report a finding by Behrman (2005) that 60 % of clinicians using\nacoustic analysis did not examine the voice signal first to see whether\nperiodic analysis was possible [@ludlow2018measuring, p. 378].\n\nSignal typing is that check. It sorts voice signals by how periodic they are\nover the interval to be analysed, so that each measure is applied only where it\nis valid.\n\n## Origin\n\nThe classification comes from the Workshop on Acoustic Voice Analysis, held on\n17 and 18 February 1994 in Denver, Colorado, whose summary statement was\nwritten by Titze [@titze1995workshop, p. 2]. The statement presents the\nclassification as central to all other considerations in acoustic voice\nanalysis, and as following the general principles of the nonlinear dynamics of\ncoupled oscillators [@titze1995workshop, p. 19]. Its first recommendation is\nthat it is useful to classify acoustic voice signals into three types\n[@titze1995workshop, p. 26].\n\nBaken and Orlikoff adopted Titze's three categories for clinical use and added\nsubtypes within each [@baken2000clinical, p. 152]. Sprecher and colleagues\n(2010) proposed a fourth type, for signals predominated by stochastic noise,\nwhich are unsuitable for both perturbation and correlation dimension analysis\n[@sprecher2010typing, p. 3710]. They classified 40 voice samples into the four\ntypes from narrowband spectrograms, and found that perturbation, perceptual\nand correlation dimension measures all worsened from Type 1 through Type 4\n[@sprecher2010typing, p. 3710].\n\n## The types\n\nThe definitions for Types 1 to 3 are Titze's [@titze1995workshop, p. 19]. The\nsubtypes are Baken and Orlikoff's addition and are shown in italics\n[@baken2000clinical, p. 152].\n\n### Type 1: nearly periodic\n\nNearly periodic (or, in the ideal case, periodic) waveforms that do not\nundergo qualitative changes during the interval analysed. Any modulating or\nsubharmonic frequencies present have at least one order of magnitude less\nenergy than the fundamental [@titze1995workshop, p. 19; @baken2000clinical, p. 152].\n\n- *Subtype A*: minor random variation of F0 or waveshape.\n- *Subtype B*: minor monotonic modulation, with F0 or amplitude steadily\n  increasing or decreasing.\n- *Subtype C*: minor cyclic variation (modulation) of F0 or amplitude.\n\n[@baken2000clinical, p. 152]\n\n### Type 2: organised, but no single F0\n\nSignals with sudden qualitative changes (bifurcations) in the interval\nanalysed, or with modulating or subharmonic frequencies whose energy is\ncomparable to that of the fundamental. Type 2 signals are clearly ordered and\norganised, but no single F0 value validly characterises the whole segment\n[@titze1995workshop, p. 19; @baken2000clinical, p. 153].\n\n- *Subtype A*: signal bifurcation(s) present.\n- *Subtype B*: F0 or amplitude discontinuity.\n- *Subtype C*: large-scale modulation of F0.\n\n[@baken2000clinical, p. 153]\n\nA common Type 2 pattern is period doubling. Successive cycles alternate between\ntwo shapes, which puts a component at half the fundamental (F0/2) into the\nspectrum. The waveform then has two defensible periods: one per oscillation or\none per pair [@baken2000clinical, p. 151].\n\n### Type 3: no apparent periodicity\n\nSignals without apparent periodicity, and hence not validly susceptible to F0\nmeasurement. A Type 3 signal may nonetheless be chaotic, with a covert\norganising principle that the techniques of dynamical systems theory might\nreveal [@titze1995workshop, p. 19; @baken2000clinical, p. 153].\n\n- *Subtype A*: no observable structure.\n- *Subtype B*: deep-level (chaotic) organisation.\n\n[@baken2000clinical, p. 153]\n\n### Type 4: dominated by noise\n\nType 4 was added by Sprecher and colleagues for signals predominated by\nstochastic noise characteristics, split off from Type 3\n[@sprecher2010typing, p. 3711]. Such signals have an infinite correlation\ndimension, which is what makes them unsuitable for the nonlinear methods that\ncan still describe a Type 3 signal [@sprecher2010typing, p. 3710].\n\nOn a narrowband spectrogram a Type 4 signal shows energy smeared across a\nbroad range of frequencies, as with broadband white noise; an F0 may or may\nnot be visible [@sprecher2010typing, p. 3711]. A Type 3 signal, by contrast,\nshows smearing across the harmonics with the energy concentrated at lower\nfrequencies, generally below about 1500 Hz, and often still shows F0 and one\nor two harmonics [@sprecher2010typing, p. 3711].\n\nAdding Type 4 also narrows Type 3. Sprecher and colleagues define Type 3 as\nchaotic with a finite dimension, where Titze defined it as any signal with no\napparent periodic structure [@sprecher2010typing, p. 3711;\n@titze1995workshop, p. 19]. The four-type scheme is a subdivision of Titze's\nType 3 rather than a disagreement about the signals themselves.\n\n## What the types look like\n\n@fig-types shows one synthetic example of each type. Each is a pulse train\npassed through the same vowel filter; only the cycle-to-cycle pattern differs.\nThe spectrograms use a long window, so harmonics show as horizontal lines when\nthey exist.\n\n::: {#cell-fig-types .cell execution_count=2}\n``` {.python .cell-code}\nsplit_t = 0.4 * 0.6\nfig, axes = plt.subplots(4, 2, figsize=(7.2, 7.6),\n                         gridspec_kw={\"width_ratios\": [1, 1.35]})\nfor row, (name, x) in enumerate(examples.items()):\n    aw, asg = axes[row]\n    t0 = 0.40  # waveform excerpt start (s), after the Type 2 bifurcation\n    seg = x[int(t0 * FS): int((t0 + 0.06) * FS)]\n    aw.plot(np.arange(len(seg)) / FS * 1e3, seg, color=vs.INK, lw=0.8)\n    aw.set_ylim(-1.05, 1.05)\n    aw.set_yticks([])\n    aw.set_title(name, color=vs.INK)\n    vs.style_axes(aw, grid=False)\n    aw.spines[\"left\"].set_visible(False)\n\n    vs.plot_spectrogram(asg, x, FS, win_s=0.050, fmax=1500, hop_s=0.002, dyn_db=50)\n    asg.set_ylim(0, 1.5)\n    asg.set_ylabel(\"kHz\")\n    if name == \"Type 2\":\n        asg.axvline(split_t, color=vs.ORANGE, lw=1.2, ls=\"--\")\n        asg.text(split_t + 0.01, 1.38, \"bifurcation\", color=vs.INK, fontsize=8)\n    vs.style_axes(asg, grid=False)\naxes[-1, 0].set_xlabel(\"Time (ms)\")\naxes[-1, 1].set_xlabel(\"Time (s)\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Synthetic examples of the four signal types. Left: 60 ms of waveform. Right: narrowband spectrogram (50-ms Hamming window, 0–1.5 kHz) of the whole 0.6-s segment. Type 1: small random period and amplitude variation; harmonics are clean lines. Type 2: a bifurcation at 0.19 s (shaded) from period-1 to period-2 behaviour; new lines appear midway between the harmonics, at odd multiples of F0/2. Type 3: cycle lengths and amplitudes driven by a deterministic chaotic map; no stable harmonic lines. Type 4: weak irregular pulses buried in noise; energy is spread across frequency.](foundations-signal-typing_files/figure-html/fig-types-output-1.png){#fig-types width=782 height=825 fig-alt='Four rows, one per signal type. Each row has a short waveform on the left and a spectrogram on the right. Type 1 shows a regular waveform and parallel harmonic lines. Type 2 shows alternating big and small cycles and, after about 0.19 seconds, extra lines between the harmonics. Type 3 shows irregular cycles and a smeared spectrogram. Type 4 shows a noise-like waveform and a diffuse spectrogram.'}\n:::\n:::\n\n\n## Applying the classification\n\nThe type belongs to an analysis interval, not to a speaker or a diagnosis. Both\nType 1 and Type 2 are defined by what happens during the interval to be\nanalysed [@baken2000clinical, pp. 152--153], so the same phonation can contain\na Type 1 stretch and a Type 2 stretch. The practical question is always whether\nthe segment you intend to measure is Type 1.\n\nLudlow, Kent and Gray describe the procedure. Select a segment of a prolonged\nvowel that is quasiperiodic, so that the periods of vibration can be detected\naccurately. Examine it with a narrowband spectrogram to see whether F0 and its\nharmonics are visible. If they cannot be identified, the signal is probably\nType 3 or Type 4 and is not suitable for perturbation analysis\n[@ludlow2018measuring, p. 378].\n\n@fig-tracker shows why the inspection cannot be delegated to the software. A\nsimple autocorrelation F0 tracker without a voicing decision returns a value\nfor every frame of every example. Only the Type 1 values describe the signal.\n\n::: {#cell-fig-tracker .cell execution_count=3}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 4, figsize=(7.2, 2.6), sharey=True)\nfor ax, (name, x) in zip(axes, examples.items()):\n    tt, f0 = vs.ac_f0_track(x, FS)\n    ax.axhline(125, color=vs.MUTED, lw=0.8, ls=\"--\")\n    ax.plot(tt, f0, \"o\", color=vs.BLUE, ms=3)\n    ax.set_title(name, color=vs.INK)\n    ax.text(0.04, 0.03, f\"mean {np.mean(f0):.0f} Hz\\nSD {np.std(f0):.1f} Hz\",\n            transform=ax.transAxes, va=\"bottom\", fontsize=8, color=vs.INK)\n    ax.set_xlabel(\"Time (s)\")\n    vs.style_axes(ax)\naxes[0].set_ylabel(\"Reported F0 (Hz)\")\naxes[0].set_ylim(0, 420)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![F0 returned every 10 ms by a naive autocorrelation tracker (40-ms frames, search range 60–400 Hz, no voicing decision) for the four synthetic signals of @fig-types. The dashed line is the 125-Hz rate of the pulse generator. Every frame gets a number. Type 1: the numbers describe the signal. Type 2: after the bifurcation the tracker settles on about 137 Hz, the rate of the shorter cycle of each pair; it describes neither the alternating pattern nor the 62.5-Hz pair rate. Types 3 and 4: the numbers are produced by the algorithm, not by any period in the signal.](foundations-signal-typing_files/figure-html/fig-tracker-output-1.png){#fig-tracker width=782 height=275 fig-alt='Four small panels of F0 against time. Type 1 is a flat line at 125 Hz. Type 2 is flat at 125 Hz, then steps up to about 137 Hz. Type 3 scatters between about 95 and 150 Hz. Type 4 jumps between widely different values up to 400 Hz.'}\n:::\n:::\n\n\n@fig-workflow summarises the decision.\n\n```{mermaid}\n%%| label: fig-workflow\n%%| fig-cap: \"Signal-typing workflow before measurement. Branch labels follow the definitions of Baken and Orlikoff (2000, pp. 152–153) and the inspection procedure described by Ludlow, Kent and Gray (2018, p. 378).\"\nflowchart TD\n    A[\"Select a quasiperiodic segment<br/>of the sustained vowel\"] --> B[\"Inspect the waveform and a<br/>narrowband spectrogram\"]\n    B --> C{\"F0 and harmonics<br/>visible?\"}\n    C -- \"No\" --> G[\"Type 3 or 4:<br/>no F0-based measures\"]\n    C -- \"Yes\" --> D{\"Qualitative change, subharmonics,<br/>or strong modulation<br/>in the interval?\"}\n    D -- \"No\" --> E[\"Type 1:<br/>F0, perturbation and<br/>noise measures apply\"]\n    D -- \"Yes\" --> F{\"Can a shorter Type 1<br/>segment be isolated?\"}\n    F -- \"Yes\" --> A\n    F -- \"No\" --> H[\"Type 2:<br/>report perturbation as<br/>not applicable\"]\n    G --> I[\"Use measures that do not<br/>need F0, such as CPPS;<br/>describe the signal\"]\n    H --> I\n```\n\n## Which measures apply to which types\n\n| Type | F0 | Perturbation (jitter, shimmer) |\n|---|---|---|\n| 1 | The definition of F0 is unambiguous only for Type 1 signals [@titze1995workshop, p. 26]. Evaluation of F0 presupposes Type 1, subtype A, within reasonable limits [@baken2000clinical, p. 153]. | Considerable utility and reliability [@titze1995workshop, p. 26]. |\n| 2 | No obvious single F0 throughout the segment [@titze1995workshop, p. 19]. | Per-cycle F0 and per-cycle amplitude, and their perturbation, cannot be reliably extracted. Perturbation measures by themselves are unreliable and contain little pattern information [@titze1995workshop, p. 26]. |\n| 3 | Not validly susceptible to F0 measurement [@titze1995workshop, p. 26; @baken2000clinical, p. 153]. | Cannot be reliably extracted [@titze1995workshop, p. 26]. |\n| 4 | May or may not show an F0 on the spectrogram [@sprecher2010typing, p. 3711]. | Not reliable, and the signal is unsuitable for correlation dimension analysis as well [@sprecher2010typing, p. 3710]. |\n\n: What each signal type supports. {#tbl-type-measures}\n\nFour points of detail behind the table.\n\n- **How much perturbation is still reliable.** Titze's practical guideline for\n  Type 1 signals is that perturbation measures below about 5% have been found\n  reliable [@titze1995workshop, p. 26].\n- **Where the contour breaks.** Average cyclic parameter contours can be\n  extracted from both Type 1 and Type 2 signals, but where a bifurcation\n  occurs in a Type 2 signal, arbitrary decisions by the extraction algorithm\n  are likely to affect the contour in a non-unique way\n  [@titze1995workshop, p. 27]. Event-based contours are highly susceptible to\n  error in Types 2 and 3. They may be used for visual display, but are not\n  recommended for perturbation measures on Type 3 signals\n  [@titze1995workshop, p. 27].\n- **An empirical cutoff.** Sprecher and colleagues used the TF32 unreliability\n  measures trk and err, taking an err above 10 to mark a sample ill-suited to\n  perturbation analysis [@sprecher2010typing, p. 3711]. Percent jitter and\n  percent shimmer rose and SNR fell from Type 1 to Type 4, and both trk and\n  err grouped Types 1 and 2 together against Types 3 and 4, with no\n  significant difference between Types 3 and 4\n  [@sprecher2010typing, p. 3713].\n- **What to use instead.** For Type 2, visual displays are the most useful,\n  and assessment is best based on the entire display rather than a single\n  measure [@titze1995workshop, p. 26]. For Type 3, perceptual ratings of\n  roughness and of other auditory manifestations of aperiodicity are likely\n  the best clinical measures, with fractal dimension, attractor dimension or\n  the Lyapunov exponent as possible acoustic complements, and phase portraits\n  as visual confirmation of high dimensionality [@titze1995workshop, p. 26].\n  For Type 4, correlation dimension could not be calculated at all, the curves\n  failing to converge, and spectrographic and perceptual analysis remain valid\n  but yield no objective quantitative data\n  [@sprecher2010typing, p. 3714; @sprecher2010typing, p. 3715].\n\nOther measure families relate to the types as follows.\n\n- **Harmonics-to-noise ratio.** HNR needs a filter that separates F0 and its\n  harmonics from the rest of the signal. Like jitter and shimmer, it can only\n  be applied to a steady phonation such as a prolonged vowel\n  [@ludlow2018measuring, p. 378]. It therefore shares their dependence on a\n  Type 1 segment.\n- **Cepstral peak prominence.** CPP does not require direct computation of\n  F0, and it can be extracted from connected speech as well as sustained\n  vowels [@murton2020cpp, p. 1596]. Because no pitch detection or tracking is\n  used, the cepstral measures are robust in dysphonic voices, particularly\n  breathy ones [@barsties2018meta, p. 316]. The 2018 ASHA guidance recommended\n  CPP as a general measure of dysphonia in place of jitter, shimmer and HNR\n  [@murton2020cpp, p. 1596]. See the [CPPS chapter](cpps.qmd).\n- **Composite indices.** AVQI includes shimmer local, shimmer local dB, and\n  HNR among its components [@barsties2016avqi, p. 574]. ABI includes jitter\n  local [@delgado2018avqi, p. 320]. These components carry the restrictions in\n  @tbl-type-measures into the composite. See the [AVQI](avqi.qmd) and\n  [ABI](abi.qmd) chapters.\n- **Dynamical-systems methods.** For Type 3 signals, any covert organisation\n  might be discoverable with the techniques of dynamical systems theory\n  [@baken2000clinical, p. 153].\n\n## Caveats\n\n- **Typing is a judgement.** The types are defined by inspection, and the\n  boundary between Type 1 and Type 2 is stated as an energy ratio (an order of\n  magnitude below the fundamental versus comparable to it)\n  [@titze1995workshop, p. 19; @baken2000clinical, pp. 152--153]. None of the\n  ingested sources reports inter-rater agreement for signal typing itself. In\n  Sprecher and colleagues the typing was done by one author with consultation\n  from the others, and the Spearman correlation of 0.867 they report is for\n  their three listeners' perceptual ratings, which are a separate judgement\n  [@sprecher2010typing, p. 3711; @sprecher2010typing, p. 3713]. They also note\n  that the cutoff for strong modulations is somewhat subjective, and excluded\n  wavy-harmonic samples for that reason [@sprecher2010typing, p. 3711].\n- **Perturbation can move the wrong way with treatment.** When a voice is very\n  irregular before treatment, few periods can be tracked, and jitter and\n  shimmer may come out low. As the voice improves, more periods are\n  identified and the measured values may rise\n  [@ludlow2018measuring, p. 378]. Type the signal at every session before\n  comparing perturbation values over time.\n- **Occasional discontinuities.** Occasional discontinuities may be less\n  damaging to perturbation measurement than was once believed, at least for\n  some software [@baken2000clinical, p. 153]. The requirement for a Type 1\n  segment still stands.\n- **Subtypes are an extension.** The A/B/C subtypes are Baken and Orlikoff's\n  addition to Titze's three categories [@baken2000clinical, p. 152]. Cite a\n  subtype only where the analysis depends on it.\n- **The samples behind Type 4.** Sprecher and colleagues' 40 samples, ten per\n  type, were selected as the most representative of each type from about 150\n  sustained phonations in a disordered-voice database\n  [@sprecher2010typing, p. 3711]. They were chosen to present the concept of a\n  Type 4 signal, not as a consecutive clinical series, and the authors defer\n  the association between pathology and type to future work\n  [@sprecher2010typing, p. 3715].\n\n## Points of disagreement\n\n- **Perturbation analysis of Type 2 signals.** Titze recommends against it:\n  for Type 2 signals, perturbation measures by themselves are unreliable and\n  contain little pattern information [@titze1995workshop, p. 26]. Sprecher and\n  colleagues found that most of their Type 2 samples fell below the err cutoff\n  of 10, and concluded that Type 1 and some Type 2 voices, those without\n  bifurcations, could be analysed with perturbation\n  [@sprecher2010typing, p. 3714]. They state that this is inconsistent with\n  Titze's recommendations and may be attributable to their own typing\n  procedure, and advise that future work consider pitch-tracking measures\n  before including Type 2 voices [@sprecher2010typing, p. 3715]. This chapter\n  follows Titze for Type 2, and @tbl-type-measures reflects that.\n- **Date of the classification.** The workshop was held on 17 and 18 February\n  1994 [@titze1995workshop, p. 2], and the summary statement carries no\n  publication year of its own. Baken and Orlikoff cite the scheme as Titze\n  (1995) [@baken2000clinical, p. 152]; Ludlow, Kent and Gray cite it as Titze\n  (1994) [@ludlow2018measuring, p. 378]; Sprecher and colleagues cite it as\n  Titze (1995) [@sprecher2010typing, p. 3710]. This reference uses 1995, the\n  more common form, and gives the workshop date where it matters.\n- **Character of Type 2 and Type 3 in the secondary accounts.** Baken and\n  Orlikoff define Type 2 by bifurcations or strong modulating or subharmonic\n  components, and Type 3 by the absence of apparent periodicity, possibly with\n  chaotic organisation [@baken2000clinical, p. 153]. Ludlow, Kent and Gray\n  describe Type 2 as highly irregular periodicity with subharmonics and\n  modulations such as tremor, and Type 3 as chaotic and usually perceived as\n  rough [@ludlow2018measuring, p. 378]. Both are compatible with Titze's\n  wording [@titze1995workshop, p. 19], which this chapter now uses directly.\n\n",
    "supporting": [
      "foundations-signal-typing_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}